package.json
test/database/financialreport.js

The fre test was failing because the dev database created by build_app doesn't have accounting periods in 2015. This fixes that by creating accounting periods in the current year.
The change to `package.json` allows running the database tests in isolation, which will become more useful in the next month or so as the number of stored procedure and trigger tests grows.

fix test failures that started around the new year

---

database/source/xm/javascript/user_preference.sql

Easy way to persist and retrieve user preferences via REST. The user is assumed to be whatever user is making the request. Note that we persist to `xt.userpref` and not `public.usrpref`. 
```
$.ajax({
url: '/' + org + '/browser-api/v1/services/user-preference/commit-preference',
type: "POST",
dataType: "json",
data: {
attributes: [
"my_userpref_name",
"my_userpref_value"
]
}
});
```
```
$.ajax({
url: '/' + org + '/browser-api/v1/services/user-preference/get-preference',
type: "POST",
dataType: "json",
data: {
attributes: [
"my_userpref_value"
]
}
});
```

Expose user preferences to REST

---

node-datasource/controllers/ImapController.js
node-datasource/main.js
node-datasource/sample_config.js
package.json
scripts/cache_email.js

Not ready for pull yet, and destined for 4.9, but worthwhile opening for discussion.
This code exposes a REST endpoint to show all messages to/from a particular email address. The way the Qt client would consume this endpoint would be that there'd be an email tab in the contact workspace (something similar could be set up for accounts, too) that would make a HTTP request to this endpoint, and would render the resultant JSON however it sees fit.
Configuration options: 
1. The simplest way to set this up is to go into your mail server, add an archive-y email address, bcc all communication to that address, and then enter into our system the creds for that address. The imap search can be done in real time on that address without the need to put anything in a table in our database.
2. Option 1 …

Email integration

---

scripts/lib/util/default_extensions.js

No need to pull this until dashboard-anything is more ready, but this is all that's necessary to put dashboard-anything into new installations.
To get it onto existing installs, execute this command (even though that directory won't exist yet):
```
$ ./scripts/build_app.js -d demo_dev -e node_modules/xtuple-dashboard-anything
```

add dashboard-anything to default extension list

---

lib/enyo-x/source/widgets/input.js
lib/enyo-x/source/widgets/number.js

Needs to be tested on mobile (ideally TC-55) device to be sure that the numeric keyboard displays, not the text keyboard.

Make quantity input type: DecimalInput

---

foundation-database/public/functions/cntctdups.sql

Replace SELECT * with explicit column names in cntctdups() function.

Issue #22886: Fixes uuid problem with Contact Merge utility.

---

scripts/xml/postbooks_package.xml

testing upgrade to 4.9.0Beta was failing the prereq check because the string `4.10.0` is less than `4.9.0`

lexicographic order ain't numeric order

---

foundation-database/manifest.js
foundation-database/public/functions/_normalizeversion.sql
foundation-database/public/functions/compareversion.sql
test/database/functions/.jshint
test/database/functions/compareversion.js

Issue #24213: Revised compare version function
The new version should be callable from the Updater to compare package versions and from updater packages themselves in version number prerequisite checks. Thus
```sql
select not fetchMetricText('ServerVersion') > '4.9.0';
```
can be replaced with
```sql
select compareVersion(fetchMetricText('ServerVersion'), '4.9.0') = -1;
```
The new select is a little longer but avoids the `<` encoding issue. It also handles alpha/beta/rc/final queries and transitions between X.9.Y and X.10.0.

issue #24213 - expand compare versions function

---

foundation-database/public/functions/numofdatabaseusers.sql
foundation-database/public/functions/numofserverusers.sql

This pull request addresses part of the problems describe in Issue #25072. It also compliments and is required by PR xtuple/qt-client#625.
The *numOfDatabaseUsers* function has been revised to perform connection counting against the "application_name" assigned to the database connection. An overload has been provided to retain backwards compatibility, though a scan of the major repositories showed no references to this stored procedure except for in the qt-client.
The "numOfServerUsers" function has been updated to count only connections for the active database which compliments the established licensing rules and clarifies the connection count reporting displayed by the **System** > **Setup** > **Database** screen.

Issue #25072: Purchased xTuple licenses are consumed by non xTuple DB connections

---

enyo-client/application/source/views/list.js
enyo-client/extensions/source/project/client/widgets/parameter.js
enyo-client/extensions/source/purchasing/client/en/strings.js
enyo-client/extensions/source/purchasing/client/widgets/parameter.js
enyo-client/extensions/source/sales/client/en/strings.js
enyo-client/extensions/source/sales/client/widgets/parameter.js
lib/enyo-x/source/views/list.js
lib/enyo-x/source/views/list_base.js
lib/enyo-x/source/views/module_container.js
lib/enyo-x/source/views/navigator.js
lib/enyo-x/source/views/transaction_list_container.js

- Added an `alwaysRefetch` published value and set it to true on the Activity List so that every time it's rendered in the client it re-fetches. The onModelChange event used to "refresh" lists is not working here - transactional enyo views would need a lot of work to add the missing functionality, thus this `alwaysRefetch` solution.
- Renamed the _workflow_ labels in the Activity List parameter widget
UAT:
*on a db with workflow setup 
1. Access the activity list from sales module (so that it fetches for the first time as normal, this still takes a long time).
2. Go back to Sales Order list, add a sales order
3. Go back to activity list and see that the sales order should now appear in the list
4. Tap on `Issue to Shipping` workflow for the sales order that was created, issue all line …

2207 refresh activity list

---

foundation-database/public/trigger_functions/aropen.sql

Resolves issue where user able to process payments in a Sales Order cannot complete the transaction due to missing privileges when creating the AR Credit memo.
This resolves both Credit Card and Cash payments

Issue #24608: Allow creation of CM when posting payments inside SOs

---

database/orm/models/contact.json

This fixes a bug when querying the `XM.ContactRelation` object using share user access. The permission check was looking for a nested object property `account.number`, but this is not a nested object, only the natural key is available, so the permission check should just be for `account`.
See different between `owner` and `account` on `XM.ContactRelation`.

Account is not nested. Should be just nkey, not sub prop.

---

foundation-database/public/functions/releasenumber.sql

Resolve another use-case scenario around multiple open documents and their numbering

Issue #24589: Handle doc number release when Quotes use SO numbering

---

foundation-database/public/tables/priv.sql

Add separate privilege to SO hold type to allow user to create a SO but not necessarily override customer credit hold
Requires xtuple/qt-client#647

Issue #12336: Add SO Hold Type override privilege

---

lib/enyo-x/source/layout/panels.js
lib/enyo-x/source/views/navigator.js
lib/enyo-x/source/views/search.js
lib/enyo-x/source/views/transaction_list.js
lib/enyo-x/source/views/transaction_list_container.js

Adds a grabber and makes draggable both search lists and transaction lists.
**Before:**
**After:**

resolves issue #2264 - make transaction lists draggable

---

foundation-database/manifest.js
foundation-database/public/tables/metasql/saletype-table.mql
foundation-database/public/tables/saletype.sql

SO defaulted to first alphabetically listed Sale Type when not manually set.  This could change if Sale Types were updated.
Must be merged together with xtuple/xtuple#2261
Required by xtuple/qt-client#649

Issue #25612: Add Sale Type default checkbox to set up to fix SO bug

---

.travis.yml
foundation-database/manifest.js
foundation-database/public/indexes/charass.sql

reduce seq scans, items-detail runtime in a real customer db from 884ms to 444ms

issue #24001: reduce seq scans, items-detail runtime

---

test/database/gotchas.js

this should allow https://github.com/xtuple/private-extensions/pull/589 to get past the basic database test

handle public and xt(core) potype tables for now

---

lib/enyo-x/source/views/transaction_list.js

There was an issue where, if a sales order has multiple line items of the same item number, the scanning would never reduce the list to a single line/issue the qty. This corrects that scenario and also handles remaining <1 balance qty.

handle duplicate items

---

foundation-database/manifest.js
foundation-database/public/tables/itemuomconv.sql
foundation-database/public/tables/metasql/uoms-item.mql

Allow Item UOM conversion to be deactivated (not deleted)
Screens previously running duplicated sql now refer to metaSQL and factor in active status

Issue #25729: Various UOM handling improvements and consistency

---

enyo-client/application/source/views/list.js

This commit https://github.com/xtuple/xtuple/commit/b3193998fb36c0c07b3adb5aa0e1bb6d40ffdcde reversed the icon-size https://github.com/xtuple/xtuple/issues/2232 *and* activity list refresh https://github.com/xtuple/xtuple/issues/2232 fixes. This PR adds them back.

re-apply activity list refresh and icon size change

---

foundation-database/public/tables/metasql/bankrec-checks.mql
foundation-database/public/tables/metasql/bankrec-receipts.mql

5 decimal places is insufficient when converting currency so switched to 6.  This was causing rounding issues for alternate currency bank accounts.
The reconcileBankAccount code formats the currency using the UOMRatio which is manually set in the Locale screen.  I am not sure this is a good idea as this ratio defaults to 5, and the user could manually set it much lower.  I think we either introduce a new decimal setup in the Locale screen or just code it differently in the Bank Rec screen.  @gilmoskowitz appreciate your thoughts here.

Issue #25836: Incorrect currency decimal places on Bank Rec screen

---

foundation-database/manifest.js
foundation-database/public/trigger_functions/trialbal.sql

Similar to gltrans table introduce trigger function to prevent Db editing of trialbal table.
Due to the nature of the trialbal table the only real check we can introduce is to check for editing closed periods.

Issue #25392: Prevent unauthorised editing of Trial Balance table

---

database/source/xt/trigger_functions/sales_order_did_change.sql

Looks like it was caused by the data.fetchMetric not being available in the desktop client.  Converted to a more traditional fetchmetric.

Issue #25777: Unable to convert Quotes to Sales Order

---

foundation-database/public/tables/metasql/bankrec-checks.mql

Remove reference to uomratio and set exchange rate to 6 decimal places to ensure sufficient decimal places in the Bank Reconciliation screen and to ensure consistency between the metaSQL and the application.

Issue #25836: Insufficient decimal places in Bank Rec screen

---

foundation-database/public/trigger_functions/invhist.sql

Prevent triggering unposted inventory transactions on historical documents from the inventory transaction information screen.
Consider related qt-client PR

Issue #19160: Edit Inventory Transaction causes probs for frozen sites

---

scripts/lib/util/send_to_database.js

Change `build_app.js` apply to database psql error output to write to a log file and console output will be:
```
./scripts/build_app.js -d test -e ../private-extensions/source/xdruple
building xdruple
info: Applying build to database test
error: Cannot install file  /home/dev/xtuple/scripts/output/build_test.sql
error: See errors in  /home/dev/xtuple/scripts/output/build_test.sql.log
################################################################################
################################################################################
psql:/home/dev/xtuple/scripts/output/build_test.sql:150: NOTICE:  function xt.iscatalogitemgrp(pg_catalog.int4) does not exist, skipping
psql:/home/dev/xtuple/scripts/output/build_test.sql:791: NOTICE:  ALTER TABLE / ADD PRIMARY KEY will create …
```

Limit psql error barfing to the last 20 lines on build_app.js

---

scripts/lib/util/convert_specialized.js
scripts/lib/util/process_manifest.js

The `manifest.js` can now optionally be formatted like this:
```
...
"databaseScripts": [
"xdruple/tables/pkgscript/uom.js",
{"path": "xdruple/tables/pkgscript/uoms.js", "order": 2},
"priv.sql"
]
...
```
When this is installed with `build_app.js` the `order` of `xdruple/tables/pkgscript/uoms.js` will be #2.

Allow manifest.js files to set a package order and grade.

---

lib/orm/source/xt/javascript/schema.sql

Our JSON-Schema includes the columns "comment" from Postgres as the description in the JSON-Schema. This worked find for basic column, but was skipped for toOne and toMany ORM relations. This PR adds support for including the description for toOne and toMany properties.
Example:
```
"XdUserContactAccount": {
"id": "XdUserContactAccount",
"type": "object",
"properties": {
"drupalUserUuid": {
"title": "Drupal User Uuid",
"required": true,
"isKey": true,
"description": "Drupal Users UUID.", <====== This was here before this PR.
"type": "string",
"format": "uuid"
},
"xdrupleSite": {
"title": "Xdruple Site",
"type": "String",
"$ref": "XdSiteRelation/name",
"required": true,
"description": "Drupal site id for this association." <====== This was added by this PR.
},
"contact": {
"title": …
```

Include description for toOne and toMany columns in JSON-Schema.

---

lib/enyo-x/source/views/transaction_list.js

On `wsgbergin` pilot db:
1. Issue to Shipping lists were taking a long time to render for orders with dozens of line items due to this refreshing of every controlled item's model: https://github.com/xtuple/xtuple/compare/xtuple:4_9_x...jcarlin:4_9_preRC_bugs?expand=1#diff-827dc86936eb428bbb05e388a0e57092L220. It turns out this was occurring at the same time that the model was still in the process of setting the `FIFO` data: https://github.com/xtuple/private-extensions/blob/4_9_x/source/inventory/client/models/transaction.js#L247
2. Issue All on a Sales Order with controlled items was not populating the Issue Stock workspace. Removing this unnecessary setting of model.transactionDate https://github.com/xtuple/xtuple/compare/xtuple:4_9_x...jcarlin:4_9_preRC_bugs?expand=1#diff-827dc86936eb428 …

req. refresh to populate FIFO data, issue all populate workspace correctly

---

lib/orm/source/xt/javascript/orm.sql

Allows for a nkey like `productAliasNumber`:
```
{
"context": "xtuple",
"nameSpace": "XM",
"type": "XdProductAlias",
"table": "itemalias",
"comment": "Product Alias Map",
"privileges": {
"all": {
"create": false,
"read": true,
"update": false,
"delete": false
}
},
"properties": [
{
"name": "id",
"attr": {
"type": "Number",
"column": "itemalias_id",
"isPrimaryKey": true
}
},
{
"name": "productAliasNumber",
"attr": {
"type": "String",
"column": "itemalias_number",
"required": true,
"isNaturalKey": true
}
},
...
```

Allow nkey ORM toMany and toOne properties to be cammelCased.

---

lib/enyo-x/source/views/module_container.js
lib/enyo-x/source/views/transaction_list_container.js

- Transaction List Container goes to content panel on small devices
- Back button added to content panel (to transaction lists) like there is on every other list
> First panel often gets in the way of UI flow. Look into "auto collapse" as a patch for this bad mobile UI design.

Transaction List Container goes to content panel on small devices

---

foundation-database/public/functions/postarcreditmemoapplication.sql

Use the source document currency rate instead of recalculating the currency to base as of the application date.

Issue #25944: AR Out of Balance when CM applied

---

lib/enyo-x/source/views/transaction_list_container.js

This https://github.com/xtuple/xtuple/pull/2359 added a new back button for small devices, in the same way that the rest of the app does, and in the new handling of the back button it wasn't missing the flag to tell the activity list to refetch.

new (small device) back button to call auto-refetch on activity list

---

database/source/xm/javascript/system.sql
enyo-client/application/source/en/strings.js
enyo-client/application/source/models/sales_order.js
enyo-client/application/source/views/workspace.js
enyo-client/extensions/source/project/client/models/project.js
enyo-client/extensions/source/purchasing/client/models/purchase_order.js

- Resolves issue #25438: add TriggerWorkflow metric to Setup > Configure > System
- Resolves issue #26001: dont create workflow in mobile if TriggerWorklow enabled
Notes:
- mobile client creates workflow items using one mechanism
- desktop client creates workflow items using a different mechanism
- if the desktop client mechanism is enabled, desktop activity generates workflow
- if the desktop client mechanism is enabled, mobile client generates workflow using _both_ mechanisms
- this PR turns off the native mobile client mechanism if the desktop mechanism is turned on so only one set of workflow data gets created
UAT:
1. Create an order that generates workflow for Sales Order, Purchase Order, Project. Verify that the workflow items are created.
2. Enable workflow through the mwc Setup > …

dont create wf in mwc when triggerworkflow metric enabled

---

enyo-client/extensions/source/purchasing/client/models/purchase_order.js

Resolved when this is pulled in and db built https://github.com/xtuple/private-extensions/pull/642 and a purchase type set on the vendor record in qt-client. 
Neither branch should be dependent on each other for Travis-CI to pass.

resolves issue #26047

---

foundation-database/public/functions/postreceipt.sql
foundation-database/public/functions/postvoucher.sql

PO Item freight was already stored in base curr.  The Post Voucher function was incorrectly converting the freight causing G/L posting errors with incorrect PO Liability entries and Incorrect freigght gain/loss entries.

Issue #25970: PO Line Item Freight in Alt currency

---

scripts/lib/build_database.js
scripts/release_build.sh

This is part three of the fix for 23834. This part uses build_app to load the current version of xtte into reference databases as we build them for a release. It depends on xtuple/xtte#15 (combines all of the xtte code in one place) and is related to xtuple/xtuple-extensions#203 (removes the now-superfluous copy).

issue #23834 - combine all te

---

foundation-database/public/functions/createdoctype.sql
foundation-database/public/patches/populate_source.sql
lib/orm/source/xt/functions/js_init.sql

Delete doctypes and recreate them on rebuild. This ensures they work with any changes we make to the underlying function, tables, views and triggers.
Add `module` parameter to `createDoctype()`.
Default `NULL` `pDocAssNum` to `0` so `source` table trigger will handle figuring out the number.

Fix invalid source table records created through createDoctype() Bug #26091

---

lib/enyo-x/source/views/list_base.js

UAT:
Shrink your web browser screen and reload app. Multi-select should be disabled across the app including the transaction lists (issue to shipping, enter receipt, etc).

26025 disable multiSelect on small device

---

foundation-database/public/functions/itemsrcprice.sql

Scenario where no item price is entered AND no Item Source exists.

Issue #25898: SQL Error on PO Quick Entry where no Item Source exists

---

foundation-database/public/functions/checkdetailformatted.sql
foundation-database/public/functions/spellamount.sql
foundation-database/public/tables/report/APCheck.xml
foundation-database/public/tables/report/CheckMultiPage.xml

Search showed spellAmount was always being used in a check scenario and always had the initcap applied so removed initcap from reports/functions and applied correct formatting inside spellAmount function.

Issue #26180: Correct Check Word formatting

---

foundation-database/public/functions/getsoscheddate.sql

getSoSchedDate(INTEGER) was selecting ALL cohead orders to get the status of one order.

CRITIAL!!! Fix getsoscheddate() performance regression. Effects all SO lists.

---

foundation-database/public/functions/_docinfo.sql
foundation-database/public/patches/populate_source.sql
foundation-database/public/trigger_functions/source.sql

Note that this is not a complete fix for 26313. There are also some changes required in the desktop client to complete that - https://github.com/xtuple/qt-client/pull/813 - but they can be merged independently.

issue #26313 - source_docass_num must match c++ enum, crmacct and child windows should show each others docass

---

npm-shrinkwrap.json
package.json

`npm shrinkwrap` picked up the new version of bcrypt that came out today. That's why it's in this PR.

Remove qr-image. It's not used anymore.

---

lib/enyo-x/source/views/list.js
lib/enyo-x/source/views/navigator.js
lib/enyo-x/source/views/transaction_list_container.js

Ready.
https://github.com/xtuple/xtuple/pull/2466's `onProcessingChanged` event clashed with transactionListContainer/transactionList's `onProcessingChanged` https://github.com/xtuple/xtuple/blob/4_10_x/lib/enyo-x/source/views/transaction_list.js#L33. The result was the inability to tap a line item and an endless loop of the list re-fetching. This pr changes the name of the new event to avoid this.

Corrects transaction list item tap failure

---

foundation-database/public/functions/updatestdcost.sql

Also resolves issue #26236
Posts a inventory value only change (nil qty. change) to inventory history so that the Inventory ledger and the General Ledger reconcile.

Issue #14182: Post InvHist record when updating Standard Cost

---

foundation-database/public/functions/qtynetable.sql

Inventory solely located in a non-netable location resulted in this function returning NULL and preventing MPS schedule from working.
@garyhgohoos would you mind checking my logic please?

Issue #26421: Fix qtyNetable function which was returning NULL 

---

lib/enyo-x/source/widgets/input.js
lib/enyo-x/source/widgets/number.js

This is fixed as desired in android. However, in iOS it is the in-line number keyboard.
Changed `XV.NumberWidget`'s type to `number` and stomped on `enyo.Input`'s `selectContents` to avoid this bug https://code.google.com/p/chromium/issues/detail?id=324360.

resolves issue #2161

---

enyo-client/application/source/views/list.js
lib/enyo-x/source/views/module_container.js
test/specs/activity.js

This bug https://www.xtuple.org/xtincident/view/bugs/24975 was previously 'resolved' by replacing the picker widget with a relational widget. This was bad design, so reverting it back to Picker while correcting the bug that was preventing proper menu display and scrolling.
UAT:
Create 4 additional users to have enough for scroll bar to display.
Activity List > gear tap Reassign User.
Should be able to scroll through the list, select a user and tap ok.
Reassign User again should properly display the list and allow for scrolling.

reassign activity item - change back to picker and correct scrolling

---

.travis.yml
lib/orm/source/xt/functions/js_init.sql
scripts/install_xtuple.sh

The var `js_type` was never defined, so `if (ns && ns[js_type]) {` always evaluated to false. This code has never even been executed. 
https://github.com/xtuple/xtuple/commit/17bc91e78583745cfb223843284d4758684f12be#diff-b85848426d86622a59a82f375bbbea5fR855
I don't think we should consider freezing all Objects:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/isFrozen
If an Object is frozen, an extension would not be able to alter an object to add additional methods/properties. e.g. `XM.Contact`. The `xTConnect` extension might want to add a `XM.Contact.sendEmail()` method or create additional properties: `XM.Contact.associatedEmails`. If we freeze the core `XM.Contact` Object when it's loaded into the `plv8` environment, extensions would not be able …

Remove js_init() Object freeze. It never worked anyway.

---

foundation-database/public/trigger_functions/trialbal.sql
test/database/triggers/trialbal.js

Retains the check for closed periods but excludes known conditions where trial balance records aer being updated.
Still not sure why Retained Earning accounts are updated in closed periods, but that is a separate issue.
Should upmerge this into 4_10 as well.

Issue #26190: Only check Trial Balance closed periods where necessary

---

foundation-database/public/functions/_docinfo.sql
foundation-database/public/types/_docinfo.sql
foundation-database/public/views/docinfo.sql
test/database/docinfo.sql

This takes a single Item Master open request for Document Associations from ~5-6 seconds down to ~250ms.
https://github.com/xtuple/qt-client/blob/b02baada16a55f215bef45f392836060782ec42b/widgets/documents.cpp#L449
This will need forward merged to `4_10_x`.
Still need to grep for all queries to `docinfo` and make sure `WHERE` clauses are used to filter by `source_id` AND `source_type`. A full `SELECT * FROM docinfo` will probably die.

Fix performance of docinfo view.

---

lib/enyo-x/source/views/grid_box.js
test/extensions/all/grid_box.js

This keyUp function is designed and currently used for line item navigation - up and down with arrow keys and down with enter key. This fix prevents navigate between line items if the current line item doesn't have all of it's required attributes (validated). 
https://github.com/xtuple/xtuple/issues/2005
Enter key still does not select an item from the popup completer, that would be nice to have, along with arrow down and up of popup list items.

resolves issue #2005 - line item triples

---

enyo-client/application/source/views/list_relations_box.js

Removes the New button from the Credit Card box in `Sales Order` workspace and `Cash Receipt` workspace. Note that, before this change, the new button is only active if the System selected credit card company is Authoize.net. This also removes the magstripe credit card functionality because  https://github.com/xtuple/xtuple/compare/4_10_x...jcarlin:1814#diff-1b24087dfcf8768cfb194946be1b2d0dR57 ensures that https://github.com/xtuple/xtuple/blob/4_10_x/enyo-client/application/source/views/workspace.js#L2680 doesn't pass (`this.$.creditCardBox.$.newButton.disabled`).

Resolves issue #1814

---

foundation-database/public/tables/metasql/orderActivityByProject-detail.mql

also tweak performance. this portion of the union went from 0.34ms to 0.28ms in a fairly small test db.

issue #26552 - try to fix the mismatched-parens side issue

---

foundation-database/manifest.js
foundation-database/public/functions/deleteso.sql
foundation-database/public/tables/docass.sql
foundation-database/public/trigger_functions/cohead.sql
foundation-database/public/trigger_functions/docass.sql

When cancelling or deleting a S/O documents/characteristics/comments remained in the Db as orphans.
This PR also resolves the issue when you delete a Document with an assigned File or URL - that file/url was also left orphaned in the database.  There was a question over whether we wanted the file to remain in the Db orphaned if it was something important.

Issue #26391: Resolve orphaned Documents/Characteristics/Comments 

---

foundation-database/manifest.js
foundation-database/public/functions/postporeturns.sql

PO Return for inventory controlled items was valuing at standard cost not Purchase Order Item price.  This means Credit Memos created as a result do not match the PO and Voucher pricing.

Issue #26757: PO Return Valuation

---

foundation-database/public/functions/numofdatabaseusers.sql

Observed a single qt-client login created multiple locks which impacts the license count.  Using distinct pids resolves this scenario while still correctly checking if a user does log in multiple times.

issue #26631, issue #26823 - Resolve license count issue when a qt-client session creates multiple locks

---

foundation-database/public/functions/postintoinvbalance.sql

Was rebuilding the invbal table (inventory AsOf reporting).  Kept crashing due to NULL inserts failing constraint.  Found where Summarised Inventory records had NULL invhist_unitcost values causing the issue.   Added COALESCE to ensure process completes.

issue #26986 - Resolve NULL inserts into INVBAL table

---

foundation-database/public/functions/copyitemsite.sql

Copies control method from originating site - needed for transfer of lot/serial information between sites

Issue #26705: ItemSite Lot/Serial control on Transfer Orders

---

foundation-database/manifest.js
foundation-database/public/functions/_docinfo.sql
foundation-database/public/functions/_gettargetdocument.sql
foundation-database/public/types/_targetdoc.sql
foundation-database/public/views/docinfo.sql
test/database/docinfo.js
test/database/docinfo.sql

This approach was suggested by @paladinlogic - query the docass and source tables to get the associations, then retrieve detail from various tables individually. The performance selecting directly from the `docinfo` view is terrible. The performance selecting from the `_docinfo(id, type)` function is much better.
Test results on one large database indicate between 1 and 5 orders of magnitude performance, depending on the particular records.
See accompanying xtuple/qt-client#1072

issue #26887 - rework _docinfo() to improve perf and eliminate redundancy

---

foundation-database/public/functions/copyaccountingyearperiod.sql
foundation-database/public/functions/createaccountingperiod.sql
foundation-database/public/trigger_functions/trialbal.sql

This includes all of the pieces up to and including https://github.com/andersdd/xtuple/commit/26349bc0b3deb803bd04cb2417af5d4c0b9758d3 even though xtuple/xtuple#2591 hasn't been merged yet (2016-02-02).

issue #27205 - backport to 4.9.3

---

foundation-database/api/views/project.sql

Everywhere else refers to status C = 'Completed'

Issue #27478: Resolve API.project inconsistency

---

foundation-database/api/views/creditmemoline.sql
foundation-database/public/functions/insertitemcost.sql
foundation-database/public/functions/updateitemcost.sql
scripts/install_xtuple.sh
test/database/functions/insertitemcost.sql
test/database/functions/updateitemcost.sql
test/database/views/creditmemoline.js

9.5 complained about mismatches between the number of `%` and the number of arguments passed to a `RAISE` statement. Added a couple of tests and removed some dead code.

issue #27541 - postgres 9.5 raise needs arg counts to agree

---

foundation-database/public/functions/recallshipment.sql
foundation-database/public/functions/selectuninvoicedshipment.sql

Made the recallshipment function delete the cobill for kits instead of zero them out.  In selectuninvoicedshipment, for the case of kits, the update to a cobill is apparently non-additive whereas for other items it is additive.  Captured this distinction and applied the corresponding update to the cobill.
It is a bit tricky to reproduce the issue to begin with.  I managed to do it with a sales order containing two KCAR1 kits (separate line items).  Here are the steps I took thereafter:
1. Issued the one kit (but not the other) to shipping, shipped, and selected for billing.
2. Created the invoice.
3. Recalled the order to shipping.
4. Shipped the same kit again, selected for billing as before.
5. Issued the second kit, shipped, and selected for billing.
6. Observed the duplication while …

Issue #25038 Fixed double-billing issue for kits and odd behavior when recalling a kit to shipping

---

foundation-database/public/functions/postcheck.sql

Could not post Payments where the exchange rate changed between posting the source document and the payment itself.  
Only affects Credit Memos - this fixes the exchange gain/loss calculation.

Issue #27383: Currency Gain/Loss incorrect when posting payments

---

foundation-database/manifest.js
lib/orm/source/manifest.js
lib/orm/source/xt/functions/js_init.sql
lib/orm/source/xt/functions/raise_debug.sql
lib/orm/source/xt/functions/raise_warning.sql

plv8.elog() uses a C++ char with a hard limit of 1024 chars. This cuts off long `XT.Debug()` messages. Switch to use `RAISE DEBUG`, which is straight Postgres and has no limit.

Fix XT.Debug() length cut off

---

foundation-database/public/functions/selectpayment.sql

Otherwise, trailing digits cause trouble. `ABS(a - b) < uncertainty` would be nicer but the `<` is important here.

issue #27662 - ensure both sides of < have same precision

---

foundation-database/public/functions/voidpostedcheck.sql

Void Posted Checks in alternate bank account currency and dates.
For some reason this section of code was commented out with a statement "it does not work in all situations"  however commenting out the code was the cause of the issue #26756.
Unfortunately there is no history of this commenting out in Github so I cannot find the reasons behind it.  Is there a way to check prior history?

Issue #26756: Void Posted Checks in alternate bank account currency 

---

foundation-database/public/functions/_docinfo.sql
foundation-database/public/functions/_gettargetdocument.sql

The Documents tab in the desktop application was showing the wrong data when viewing the target record if source and targets had the same document type. This PR makes the query in `_getTargetDocument()` more precise, checking the source type and id instead of just the type.

issue #27840 - filter out the starting record

---

foundation-database/public/functions/issuewomaterial.sql
foundation-database/public/functions/postinvtrans.sql
foundation-database/public/functions/postproduction.sql

For work orders with multiple instances of the same item, have the inventory history QOH before and after columns show the correct amounts.

issue #27692 - Properly handle inventory history for work orders

---

foundation-database/public/patches/populate_source.sql

Error was resulting in the widget for a return authorization being paired with the purchaseOrder screen.  Now associating with the returnAuthorization screen.
NOTE: This pull request is paired with a corresponding pull request in private-extensions.

issue #24866 Fixed copy/paste error.

---

foundation-database/public/trigger_functions/shiptoinfo.sql

We added default configs for these to `Sales > Setup > Customer Defaults` a while ago. The PR uses those metrics to set defaults.

Issue #27962 Add trigger to set shiptoinfo defaults if they aren't provided.

---

foundation-database/public/functions/createdoctype.sql
foundation-database/public/patches/populate_source.sql
foundation-database/public/tables/source.sql

@davidbeauchamp - Could you review this please? I only added an active parameter to those source records that have a boolean field for this purpose. Let me know if you want this expanded to cover other cases:
-  `(cohead_status = 'O') as cohead_active`
-  (`lsreg_expiredate > current_date`) as lsreg_active`
- etc.

issue #28348 - add optional active flag field to source table

---

scripts/lib/util/process_manifest.js

The manifest files allow specifying either a filename or an object containing the filename and other properties describing how that file should be loaded into the database, such as grade. This auxiliary information was being stripped off. This change allows build_app.js to tweak the file paths while preserving the extra details.

issue #28447 - processing the manifest must preserve properties

---

foundation-database/public/functions/invadjustment.sql

This change accomplishes three tasks per the recorded issue: 1- Drops
the original 6 parameter version of the function; 2- Create a function
with the same code, but an extra parameter for overriding the inventory
adjustment gl account sourced from the itemsite's cost category; 3-
Coalesces the parameter value and the cost category supplied GL account
when passing parameters to the postInvTrans function call.

 	issue #28468 Add Gl Acct ID param to invAdjustment

---

foundation-database/public/functions/adjustinvvalue.sql

Prior to this change public.adjustInvValue(intger, number, integer)
would only return 0 on success or -1 on failure.  This change causes a
successful processing to return the invhist_id value of the
public.invhist record created by the function.  The function still
returns -1 on failure.

issue #28472 Update adjustInvValue return value

---

foundation-database/public/functions/adjustinvvalue.sql

This pull request is another part of my effort to bring some functional parity between the database average cost inventory valuation functionality and the inventory adjustment function.  In this case, we're bringing document number as an optional parameter to the public.adjustinvvalue function.
Please note that we also populate the invhist_ordtype and invhist_ordnumber fields rather than invhist_docnumber, the inventory adjustment function does this and so we follow its implementation.   The order type field will cause the inventory history report to show "AD-" where before it did not.  This implementation is a departure from the submitted proposal since the invadjustment implementation was misunderstood at the time.

issue #28594 - adjustinvval docnum

---

lib/orm/source/xm/javascript/model.sql
lib/orm/source/xt/javascript/data.sql
node-datasource/lib/rest-query-format/index.js

Fix some bugs in 4.10.0RC from e-comm testing.
Allows the array use case to work:
https://github.com/xtuple/xtuple/blob/4_10_x/lib/orm/source/xt/functions/get.sql#L173-L176
Fixes basic query where `parameters` is not set at all.

Fix REST API Query bug

---

foundation-database/quickstart_data.sql

Should allow XTUPLE vendor to be present in free-trial databases.
Set terms to 30 days (correct??)
Does not populate empty_data as this would require setting up default currencies/terms/vendor types

Issue #28101: Add XTUPLE Vendor and contact details to reference Dbs

---

test/specs/item_site.js

This change uses `randomUPCCode()` now:
https://github.com/xtuple/xtuple/pull/2852/files#diff-5a4b7b76fa139b3797b92c9df7ee9e6fR8353
Change the test to get the `barcode` from the `XM.Item` model vs. hard-coded, then use that for the search.

Fix CI - Should be able to search the Item through Bar Code

---

.travis.yml

This change should fix some of the CI errors we've been seeing by making sure the leading edge is merged in with the PR. It is also a more correct test run, because the PR will be merged, so we should be testing that result.

Merge in the latest master before running the tests.

---

.travis.yml

This will slow the test run down a bit, but should catch regressions.

Make sure we can re-build_app the database after an install.

---

test/specs/sales_order.js

After the latest change, https://github.com/xtuple/private-extensions/pull/857 is now failing CI because the new Sales Order that was created is getting deleted by the `crud.js` test, but the workflow tests use it.
In this repo, `XM.SalesOrder` gets flagged to `skipUpdate` and `skipDelete` for the `criud.js` tests since this change:
https://github.com/xtuple/xtuple/blame/4_11_x/test/specs/printer.js#L215
`printer.js` is not merged into the test run for `private-extensions`, so the test fails when the Sales Order is deleted and later tests try to use it.
This PR just makes the `update` and `delete` skips explicit on the `XM.SalesOrder` test and allows the test to work from `private-extensions` runs.

Don't delete the Sales Order. It's used by other tests.

---

foundation-database/public/patches/populate_source.sql

Issue is two part, with Work Order there was a typo in the privilege name, work Rental Item the "create" privilege column should be empty as those do not need to be arbitrarily created from the documents tab.

Issue #27791: Work Order and Rental Item are grayed out on "New" menu of documents tab

---

foundation-database/api/views/purchaseline.sql

Not adding tax_recoverable field as this is not available on the ui and is not implemented as yet (may never be implemented?)

Issue #28882: Add tax field to api.purchaseline

---

database/source/xt/functions/createwf.sql

Bug 29133 was caused by incorrectly converting warnings to exceptions when tracking down bug 28896. This was based on the false assumption that certain missing data ("parent" records) indicated a bug earlier in the processing. In fact those data trigger workflow generation if present but missing data should be ignored.

issue #29133 - debugging changes for issue #28896 were too aggressive

---

enyo-client/application/source/views/list.js

@xtpclark found this testing 4.10. Should back port this fix.
In mobile client, under "Setup", anything in this list did not get translated correctly because they are `kind: "XV.NameList"` inherited:
https://github.com/xtuple/xtuple/blob/4_11_x/enyo-client/application/source/views/list.js#L2826-L2891
When removing the custom `camelize()` function, `titleize()` was used because `camelize()` no longer existed.
https://github.com/xtuple/xtuple/commit/2ec85a7fb47c80e06248d65d42b9ca22db99e87e#diff-c722d458e1cf9717f15054726f196d2cR2797
The problem is, `titleize()` makes the first char capital. This PR makes it lower case so the translation strings match. We ended up with `_IncidentCategories` instead of `_incidentCategories`.

Fixes: #28966 - First char should be lowercase like old camelize()

---

foundation-database/public/trigger_functions/coitem.sql

This reverts the change made as part of PR #2644 as that was causing the duplicated characteristics.
Need to check this change with @bendiy and @rkshapiro as they need to provide the sales order line with the `coitem_imported` flag set to `true`.

Issue #29247: Revert trigger function to prevent duplicated SO characteristics

---

foundation-database/public/functions/currtobase.sql
foundation-database/public/functions/getcurrid.sql
test/database/functions/currtobase.js
test/database/functions/getcurrid.js

This is an indirect fix for 29358. The bug won't really be fixed until we have reference databases that contain these versions of the functions.

issue #29358 - pg_restore sets small search_path when refreshing materialized views

---

foundation-database/public/tables/metasql/slowMovingInventoryByClassCode-detail.mql

There's no point displaying slow moving items with no Qoh so this prevents the Div/0 potential at the same time

Issue #29391: Resolve Div/0 error in Slow Moving Stk report

---

.travis.yml
foundation-database/public/functions/usercanlogin.sql
foundation-database/public/views/usr.sql
scripts/install_xtuple.sh
test/specs/activity.js

@mdathe tested this on a database with 400,000+ `usrpref` records and saw an order of magnitude performance increase.

Fixes #29591 The `usr` view is slow on databases with lots of `usrpref` records

---

foundation-database/public/functions/postcashreceipt.sql

Resolve ambiguity in posting cash receipts via credit cards.
If no doc number was supplied on the cash receipt, the CC
transaction uses the cashrcpt_id. Trouble arises when doc numbers
and cashrcpt_ids overlap.

issue #29226 - cashreceipt docnumber takes precedence

---

foundation-database/manifest.js
foundation-database/public/functions/formatlocationname.sql
foundation-database/public/indexes/itemlocdist.sql
foundation-database/public/tables/itemlocdist.sql

Adding an index on the source id improves performance significantly.
Adding a foreign key constraint on itemlocdist_itemlocdist_id_fkey
should also help but exposes a bug in inventory distribution
cleanup.
Simplifying the formatlocationname function speeds it up by
about 10% (not much but the code is much easier to read now).

issue #29788 - itemlocdist_source_id_idx - 15min to 1.5min

---

foundation-database/manifest.js

plv8 started raising errors when running the first `language plv8` function if the init function hadn't been defined yet

fix plv8 config forward reference err

---

lib/orm/source/create_plv8.sql

some versions of plv8 seem to need the init function defined _before_ the extension is created. create a dummy version to bootstrap.

fix another plv8 config forward reference err

---

foundation-database/manifest.js
scripts/release_build.sh

requires xtdash and nodejsshim 1.0.0-rc.2, xtte 2.4.3
for those extensions to load properly. this pass expects
those repositories to be checked out at the right version
before starting the script.

prep for 4.11.0-beta - fix problems loading extensions

---

foundation-database/manifest.js
foundation-database/public/functions/fixserial.sql
foundation-database/public/patches/fixSerialColumns.sql

The bug as reported was a duplicate key on insert error on potype. The
real problem was that the sequence for potype_id was being created
with a lower number than the max potype_id as a result of data
migration. The code change in this PR tries to prevent this _kind_
of problem from arising in the future.

issue #30139 - fixSerial as part of upgrade process

---

foundation-database/public/functions/listprice.sql

With this change `listprice()` will return a "List Price" from the `item.item_listprice` column for `item_exclusive === true` Items.
`salesOrderItem.cpp` expects a `-9999.0` value, but it gets it from `itemipsprice()`, not `listprice()`:
https://github.com/xtuple/xtuple/blob/4_11_x/foundation-database/public/functions/itemipsprice.sql#L206

Fixes #30252: listprice() should work for exclusive items too.

---

foundation-database/public/tables/metasql/arOpenItems-detail.mql

refactored the query so all arapply records are considered, not just those before a particular date. this allows for smarter calculation of applications as of specific dates.

issue #30157 - calculate applicable and non-app ar applications, not filter them

---

foundation-database/public/tables/metasql/arOpenItems-detail.mql

apparently WITH clauses cannot appear in the middle of a union.
also remove some unused lines and reduce redundancy.

issue #30387 - fix regression in fix to issue #30157

---

foundation-database/public/views/orderhead.sql
foundation-database/public/views/orderitem.sql

Remove unneeded `SELECT DISTINCT *` on orderhead. 
Move `LEFT OUTER JOIN vendinfo` to column sub query improves performance with `private-extensions` version from 7.5 seconds to 500 ms.

issue #30486 - deleteitemlocdist perf

---

foundation-database/manifest.js
foundation-database/public/indexes/drop_duplicates.sql

Duplicates typically came from the 440 schema, so added a drop script rather than just removing from 440 _schema in order to effect change in upgrade scripts.

Issue #19378: Drop duplicate indexes

---

foundation-database/public/functions/createpkgschema.sql

Fixes errors such as:
```ERROR: value "3422250735" is out of range for type integer CONTEXT: PL/pgSQL function "createpkgschema" line 26 at SQL statement (22003)```

Issue #30681: Update namespace oid to use BIGINT as we finally have databases which have enough objects to overflow INTEGER

---

database/source/xm/javascript/sales_order.sql

Documentation:
https://github.com/xtuple/xtuple/wiki/REST-API-Examples#example-requests
https://github.com/xtuple/xtuple/wiki/REST-API-Example:-Associate-Customer-Deposit-with-Sales-Order
@gilmoskowitz For this to work in 4.11.0, I would need to add this to the xdruple-extension as well. Should I do that?

Expose XM.SalesOrder.addPayment dispatch service to the REST API.

---

foundation-database/manifest.js
foundation-database/public/functions/_setpackageisenabled.sql
foundation-database/public/functions/disablepackage.sql
foundation-database/public/functions/enablepackage.sql
test/database/functions/_setpackageisenabled.js

This resolves the errors reported in the issue plus another issue found in testing.
I am now getting a new error when attempting to enable/reenable the `assetmaint` package
```
ERROR:  relation "dict" would be inherited from more than once
CONTEXT:  SQL statement "ALTER TABLE IF EXISTS assetmaint.pkgdict INHERIT public.dict;"
```
No other package is presenting this.  The assetmaint.pkgdict table looks subtly different in pgAdmin but not sure where pkgdict is created no not sure why this particular package has an issue

Issue #30782: Package enabling and disabling errors

---

foundation-database/manifest.js
foundation-database/public/tables/atlasmap.sql

Extend atlasmap table to allow pointing to database stored atlas map definition xml.  Defaults to File so will not affect existing csv import definitions.

Extend atlasmap table to allow for storing atlas maps in the database

---

node-datasource/lib/ext/datasource.js

The last fix disconnected the client and removed it from the pool by calling `X.pg.pools.all[JSON.stringify(this.creds)].destroy(client);`. However, the `done()` callback was still called below that, which reconnected a new client and threw off the pool count. Line 272 here:
https://github.com/xtuple/xtuple/blob/6a2718719596b1e03ac83f47d07ac9d51f56de94/node-datasource/lib/ext/datasource.js#L227-L272
That lead to the active pg connections building until the pg server hit 100 connections and stopped accepting any more.
By calling `done(err)` instead of `X.pg.pools.all[JSON.stringify(this.creds)].destroy(client);`, `destroy()` get called anyways, which was the original goal of the last commit. The call happens here:
https://github.com/brianc/node-postgres/blob/v0.14.1/lib/pool.js#L109-L113

Fixes Issue #30663 Call done(err) instead, which destroy's the client and removed it from the pool.

---

foundation-database/public/patches/populate_source.sql

requires xtuple/qt-client#1775 otherwise a segfault occurs in the document assignment widget

Issue #19555: Allow Quotes (and Return Auths) to be attached as documents

---

foundation-database/public/functions/updatememotax.sql
foundation-database/public/functions/voidapopenvoucher.sql

Still requires Tax assignment to be correctly configured otherwise GL to tax history discrepancies can occur, but makes assignment a bit more robust in the case of voided vouchers

Issue #30799: Improve relationship between voided voucher and CM tax

---

database/source/xt/views/shipheadinfo.sql

Reduce query time from 97 seconds to 142ms.
For:
https://github.com/xtuple/xdruple-extension/pull/57
https://github.com/xtuple/xdruple-extension/pull/58

Fixes #31688 Improve Shipment tracking by Sales Order Number query performance

---

database/source/xt/tables/sordtype.sql

Ran into this incident when testing xdruple-extension pre-installation with a package.gz, then web-enabling the database. I'm not sure if the error I ran into would happen in production or if it was just the web enabling steps I followed. This PR should prevent the error from happening either way.

Issue #32700 - Make sordtype_code column NOT NULL UNIQUE.

---

foundation-database/public/functions/copyitemsite.sql

Also correct SQL error when copying Item Sites over itself (new bug found in testing)

[31856] Copy Items - retain Item site location control settings.

---

foundation-database/public/views/usr.sql

The old `public.usr` view look 1:41 minutes.
The current `public.usr` view took 1:35 minutes.
This PR `public.usr` view takes 1.5 seconds.

[29591] - Simplify view query to improve performance from 1.5 minutes to 1.5 seconds.

---

foundation-database/public/functions/copyitem.sql

User costs were missed when copying items.

[33194] Copy Item user costs when copying items

---

foundation-database/public/functions/formatdate.sql
foundation-database/public/tables/metasql/workOrderSchedule-detail.mql
test/database/functions/formatdate.js
test/database/metasql/workOrderSchedule-detail.js

and improve performance when it is.
The changes to the `formatdate()` functions change the runtime of the following query significantly:
```SQL
select formatdate(gltrans_date) from gltrans limit 1000;
```
With 17K users the runtime went from 19200 ms to 560 ms in one test database.

[33596] - remove call to formatdate when it isn't needed

---

foundation-database/public/tables/metasql/opportunities-detail.mql

Uses case insensitive pattern match
Watch for conflicts merging into version 5.0

[14260] Add Opportunity Name filter to Opp List.  

---

lib/orm/source/xt/javascript/schema.sql

The Discovery Doc query is failing after installing xdruple-extension because of this change:
https://github.com/xtuple/xdruple-extension/commit/c28730463beb2c7d2f22686ec61982a8d7cf5897
This parameterization fixes that.

[33723] Change schema introspection query to parameterize the ORM column strings.

---

database/source/xt/tables/oa2client.sql
database/source/xt/tables/oa2token.sql
package.json
test/build/rebuild.js

After adding the `xdruple.oauth_2_token` and `xdruple.oauth_2_client` views, when `add_column()` runs on the `xt.oa2token` and `xt.oa2client` table, we get this error:
```sql
ERROR:  cannot alter type of a column used by a view or rule
DETAIL:  rule _RETURN on view oauth_2_client depends on column "oa2client_issued"
CONTEXT:  SQL statement "ALTER TABLE xt.oa2token ALTER COLUMN oa2token_auth_code_expires SET DATA TYPE timestamp"
```
This appears to be happening because `timestamp` is converted to `timestamp without time zone` and `add_column()`'s check for column type differences sees this as a change.
This PR fully defines the column types as `timestamp with time zone` and drops the dependent views before running `add_column()`. Those views will then be added back later in the build …

[33899] Fully define column data type to timestamp with time zone

---

foundation-database/public/functions/_docinfo.sql
foundation-database/public/functions/buildsearchpath.sql
foundation-database/public/functions/packageisenabled.sql
foundation-database/public/tables/custinfo.sql

- Simplifying queries often makes them faster
- Indexing `cust_number text_pattern_ops` lets the customer cluster completer use an index instead of running table scans

[25224] misc performance tweaks

---

scripts/release_build.sh

This should fix recent build failures on the 4_12_x db

build 4_12_x with a version of xtte without the crm changes for 5_0_x

---

scripts/keygen.js
scripts/sql/application.sql
scripts/sql/oauth2client.sql

Script can be run same way as `build_app.js`:
```
DATABASE=pilot
CONFIG_DIR=/etc/xtuple/${DATABASE}
APPLICATION=pilot.example.com
ISSUER=pilot
KEY=pilot
./scripts/keygen.js \
-c ${CONFIG_DIR}/config.js \
-d ${DATABASE} \
-a ${APPLICATION} \
-i ${ISSUER} \
-p /var/xtuple/keys/${KEY}.p12
```
This can be used to replace https://github.com/xtuple/xtuple-admin-utility/blob/master/functions/oatoken.fun and related calls.

[34009] Turn KeyGen script into a console application with a DB connection

---

foundation-database/public/trigger_functions/incdt.sql

Data integrity checks still exist in cpp code but had to be removed from the Trigger when partially saving an incident.

[34055] Resolve partial save trigger SQL errors on new Incident

---

foundation-database/public/functions/postvoucher.sql

Check if voucher has an item with no tagged receipts or has an item with no distributions.
If so raise exception.
Also added translations for all exceptions in storedProcErrorLookup.cpp

[33376] added check to postVoucher

---

foundation-database/public/functions/createfile.sql
foundation-database/public/functions/createurl.sql
foundation-database/public/views/url.sql

The bug (as far as I can tell) is the result of the postbooks DB being initialized to a state that causes an error when rows are added to the `urlinfo` table.
This is because (after a fresh postbooks DB restore): 
- `urlinfo` starts off with 1 row, with `url_id = 4`
- the `url_id` is generated by the sequence `urlinfo_url_id_seq` which starts at 2 
Therefore, at some point as rows are added to `urlinfo` we will try to insert a row with `url_id=4` when there is already one in the table, causing the error message.
This is also the reason I was able to reproduce the error dialog, by attaching a WebSite to a incident's document.
I noticed during my testing that `url_id` and `file_id` were not following the same sequence, because the `createFile` and `createUrl` functions would call nextval() …

[34150] In ‘Copy Item’ screen, while copying the Item ‘Error Copying Item’ error dialog is displayed.

---

lib/orm/source/xt/javascript/parsemetasql.sql
lib/orm/source/xt/pegs/metasql.peg

Fixes the `foreach` array bug, 34362
Fixes the `else` required for `elseif` bug, 31820, 26912
Allows all `elseif`, `else if` and `elsif` combinations, 26914, 26913

[34362][26913][31820][26914][26912] Fix open MetaSQL PEG Parser bugs.

---

foundation-database/public/tables/metasql/packingList-getreport.mql

Found this bug when working on something else.  Been around for at least 5 years so I think this entire section of code is probably not used otherwise this would have been a problem much earlier.
However it _does_ allow for customer specific Packing List forms which is desired functionality (see issue #28314) so we probably need to revisit this code and make it work.

Fix sql bug in PackingList getreport metaSQL

---

foundation-database/public/functions/calcshipfreight.sql

This change only affects the freight calculations when the setup has been configured to not automatically calculate freight. 
The bug is caused by the `shiphead_freight` for all shipments being equal to the total SO freight amount (`cohead_freight`).
Its not ideal, but it adds all the freight from the SO to the first shipment (`shiphead_freight`) and 0 to the rest of the shipments.

[32398] Freight doubling under specific circumstances

---

foundation-database/public/functions/calculatetax.sql

Function returned NULL if no freight taxtype id was supplied in params.  Found this when attempting to utilise via another function

Make calculatetax function more robust for when no freight is required

---

foundation-database/public/trigger_functions/pack.sql

This is only one part of #34412, please do not close it.
Fix performance issue with:
```diff
-AND NEW.pack_head_id   IN (SELECT cohead_id FROM cohead)) THEN
+AND EXISTS (SELECT true FROM cohead WHERE cohead_id = NEW.pack_head_id) THEN
-ELSEIF (NEW.pack_head_id IN (SELECT tohead_id FROM tohead)) THEN
+ELSEIF EXISTS (SELECT true FROM tohead WHERE tohead_id = NEW.pack_head_id) THEN
```
Removed unneeded `(` and `)`.
Update `RAISE EXCEPTION` per coding standards.

[34412] public.pack Trigger performance improvements and modernisation.

---

foundation-database/api/views/invoice.sql
test/database/views/invoiceline.js

Add `Site` field from `invchead` table, required for version 5.0 Tax calculation to work.
This change is required for revised Fixed Asset sales process which creates an Invoice and we need to trigger the tax calculation immediately.

[34261] Add Warehouse to Invoice header API view

---

foundation-database/public/trigger_functions/bomitem.sql

Check was only being undertaken when inserting new items, not when un-expiring existing items.
There is a scenario that exists where you attempt to expire an item that is in a recursive BOM where the check goes off and never appears to return - you have to crash out of the application.  I have not resolved that issue, but it should never occur in the first place - especially after this fix.
Backport to 4.12

 [18611] Resolve scenario that allows recursive BOM items

---

foundation-database/public/functions/issuetoshipping.sql
foundation-database/public/functions/postsoitemproduction.sql

Resolve COGS bug where a job costed item was not generating COGS entries due to not finding an appropriate item cost from the W/O.
This fix does _not_ address historic data which will be corrupted.
requires associated cpp client change
Also fixes issue #34800

[34761] Revert closing of job costed W/O to shipping transaction.  

---

foundation-database/public/functions/qtyreserved.sql
foundation-database/public/indexes/coitem.sql

There is a performance bottleneck in the `qtyreserved(itemsite_id)` function:
```sql
SELECT COALESCE(SUM(coitem_qtyreserved),0) INTO _qty
FROM coitem
WHERE(coitem_itemsite_id=pItemsiteid);
```
It is slow with 300,000 rows for a matching `coitem_itemsite_id`. The `coitem_qtyreserved` is set to `0` for any coitem records that have a status of `X` (canceled) or `C` (closed) in the `_soitemTrigger()` trigger. Those records can be skipped with a `WHERE` clause and sped up with an index.
```sql
SELECT COALESCE(SUM(coitem_qtyreserved),0)
FROM coitem
WHERE coitem_itemsite_id = pItemsiteid
AND coitem_status <> ALL ('{X,C}'::bpchar[]);
```
After this change, the original query runs in 75.652 ms from a cold cache vs 72 seconds.

[34802] Fix qtyreserved() performance issue on large databases.

---

foundation-database/public/functions/copyso.sql

Also resolves the costing of copied sales orders (initially set to zero) as costing comes from the work order which has yet to process any items and therefore determine costs.

[34801] Copy S/O was not copying the characteristic pricing over.

---

foundation-database/public/tables/metasql/projects-detail_nohierarchy.mql

Was originally pointing to CRM Account contact so is not technically a bug, but was confusing for the user.  Checked 4.12 and it (recently) points to the project contact so this change makes it consistent between 4.12 and 5.0

[34979] Modify the Project Contact detail source in Projects List

---

foundation-database/public/functions/_docinfo.sql

as they have no corresponding ID to reference

[35087] Restrict child document search for USERs 

---

foundation-database/public/functions/createpr.sql

When a user does not have `OverrideTax` priv, the `coitem_taxtype_change` trigger causes a cascade of updates to coitem which ends up creating two PRs for one line on a order.
Similar to how `createpurchasetosale()` checks for an existing PO before creating one, make `createpr()` check for an existing PR before creating one. This prevents the duplication of PRs.
Also cleanup the `createpr()` functions to reduce the duplication and follow latest coding standards.

[34848] Cleanup createpr(). Check for existing PR before creating it.

---

foundation-database/public/functions/calcinvoiceamt.sql
foundation-database/public/functions/calcsalesorderamt.sql
test/database/functions/calcinvoiceamt.js
test/database/functions/calcsalesorderamt.js

by explicitly dropping them and replacing them with overloads that use default parameters.
added tests, which revealed inconsistencies in behavior when given non-existent orders/invoices.
accompanied by https://github.com/xtuple/private-extensions/pull/1098

[35088] ensure old functions get dropped

---

foundation-database/public/tables/metasql/contacts-detail.mql

Based this fix on [Chris' fix](https://github.com/xtuple/xtuple/pull/3673/commits/745a851257067d9400da0a69aee0f6b3be4fc425)
An alternative fix (though I'm not sure how correct it is) is to 
`join cntcteml where cntcteml_cntct_id=cntct_id AND cntcteml_primary`

[35217] *Contact List duplicate entries
