foundation-database/public/trigger_functions/addr.sql, foundation-database/public/trigger_functions/cntct.sql, foundation-database/public/trigger_functions/cohead.sql, foundation-database/public/trigger_functions/coitem.sql, foundation-database/public/trigger_functions/crmacct.sql, foundation-database/public/trigger_functions/cust.sql, foundation-database/public/trigger_functions/custtype.sql, foundation-database/public/trigger_functions/emp.sql, foundation-database/public/trigger_functions/incdt.sql, foundation-database/public/trigger_functions/invchead.sql, foundation-database/public/trigger_functions/item.sql, foundation-database/public/trigger_functions/ophead.sql, foundation-database/public/trigger_functions/pohead.sql, foundation-database/public/trigger_functions/poitem.sql, foundation-database/public/trigger_functions/prj.sql, foundation-database/public/trigger_functions/prjtask.sql, foundation-database/public/trigger_functions/quhead.sql, foundation-database/public/trigger_functions/quitem.sql, foundation-database/public/trigger_functions/vend.sql, foundation-database/public/trigger_functions/vohead.sql
See: https://github.com/xtuple/xtuple/pull/2047#issuecomment-68724985
=> Charass delete

enyo-client/application/source/ext/core.js, enyo-client/application/source/startup.js, lib/backbone-x/source/model.js, lib/backbone-x/source/model_mixin.js, lib/enyo-x/source/views/list.js, lib/enyo-x/source/views/transaction_list.js, lib/enyo-x/source/views/workspace.js, node-datasource/routes/generate_report.js
- Distribute to multiple locations on Enter Receipt of location controlled item returned a JSON circular structure error. This has been corrected.
- Printing multiple detail distribution for a single line item did not print the labels correctly. Now the correct qty and detail prints when transacting the item.
- Issue Line Item, Issue All now prints labels
=> Print on issue line

foundation-database/manifest.js, foundation-database/public/indexes/womatlpost.sql
Not required to build, but additional perf tweaks here:
https://github.com/xtuple/private-extensions/pull/551
=> Fix work order performance by adding womatlpost_womatl_id index.

foundation-database/public/functions/copyquote.sql
copyQuote did not copy over the characteristics properly
=> copyQuote characteristic fix

foundation-database/public/functions/formatwonumber.sql, foundation-database/public/tables/metasql/workOrderSchedule-detail.mql
we missed this in our earlier upmerges from 4_8_x to 4_9_x
=> pr2090 upmerge

foundation-database/public/functions/createaccountingperiod.sql, foundation-database/public/functions/deleteaccountingperiod.sql
Rolls forward from the latest Trial Balance entry so performance does not appear too bad.
=> Issue #25195 Forward Update Trial Balances when creating new Fiscal Periods

database/source/xt/functions/workflow_inheritsource.sql
Found issue where some scenarios returned null and therefore the rest of the function did not work correctly.
=> Resolve issue with null return on sql query

foundation-database/public/trigger_functions/crmacct.sql
=> Issue #25291: Resolve User facing errors when a CRM Account is linked

foundation-database/public/tables/metasql/crmaccounts-detail.mql
(Customer contribution)
Requires qt-client update xtuple/qt-client PR submitted
=> Issue #25451: Add account type parameter to CRM Accounts list

foundation-database/public/functions/distributeitemlocseries.sql
Needs:
https://github.com/xtuple/private-extensions/pull/573
Fixes https://github.com/xtuple/xtuple/issues/2025
=> Fix issueToShipping dispatch to work with REST API.

foundation-database/api/views/creditmemo.sql, foundation-database/api/views/creditmemoline.sql, foundation-database/api/views/invoice.sql, foundation-database/api/views/invoiceline.sql
=> Cleanup any xt.foo that should not be in xt schema.

foundation-database/public/tables/metasql/accountNumbers-detail.mql
=> Issue #25486: Add CoA filtering by Type/SubType

foundation-database/public/tables/metasql/taxHistory-detail.mql
Customer name display.
Fix problems with Purchase document amounts for AP memo and Misc. Vouchers
[HOLD] Awaiting user testing by Jim McC
=> Issue #21921: Several problems with the Tax History report.

foundation-database/public/tables/metasql/vendors-detail.mql
But still be able to handle Vendor Addresses from the Contact and the Vendor Address area
Consider together with xtuple/private-extensions#577 which handles the xwd metasql
=> Issue #25527: Fix Vendor List duplicate vendors

foundation-database/public/tables/report/Invoice.xml
Also refer to xtuple/private-extensions#578 for the changes to the xwd default Invoice
=> Issue #18047: Add Page n of Pages count back to Invoice

foundation-database/public/functions/deleteso.sql
Resolve correct release of SO number for Auto with override scenario
Requires qt-client PR xtuple/qt-client#637
=> incident #24642: Resolve correct release of SO number for Auto with overrd

enyo-client/application/source/views/list.js, lib/enyo-x/source/stylesheets/screen.css
=> resolves issue #2232 - make icon bigger

database/orm/models/sale_type.json, enyo-client/application/source/views/workspace.js, enyo-client/application/source/widgets/picker.js, foundation-database/public/tables/metasql/backlog-detail.mql, foundation-database/public/tables/metasql/opensalesorders-detail.mql, foundation-database/public/tables/metasql/partiallyShippedOrders-detail.mql, foundation-database/public/tables/metasql/salesOrders-detail.mql, foundation-database/public/trigger_functions/saletype.sql
Add parameter filter and display in list
Must be merged together with xtuple/xtuple#2262
Required by xtuple/qt-client#648
=> Issue #21642: Add Sale Type to Sales Reports

enyo-client/application/source/views/list.js, lib/enyo-x/source/widgets/relation.js, test/specs/activity.js
Picker replaced with relational widget. Start typing a user name and completer list menu should appear.
=> resolves issue #2185 - change reassign widget from picker to relational

scripts/lib/build_database.js
issue #25240 - hopefully the 2nd-to-last piece. the presumptive last piece is a separate pull request in private-extensions.
=> issue #25240 - commercialcore has to be handled like other 'foundation' extensions

foundation-database/public/tables/report/AccountNumberMasterList.xml
=> Issue #25521 CoA report does not honor filter parameters

foundation-database/public/tables/metasql/salesHistory-detail.mql, foundation-database/public/views/saleshistory.sql, foundation-database/public/views/saleshistorymisc.sql
Pre-requisite for xtuple/qt-client#660
=> Issue #24853: Add class code parameter to Sales History reports

foundation-database/public/tables/report/AROpenItem.xml
Minor tidyup of the default AR Open Item report as this was cutting off labels and data.
=> Issue #21922: Fix AR applications on AR Open Item report

.travis.yml
ran 5 times => passed 5 times, with smaller logs and in about 2/3's the time.
=> see if switching from xtuple-server back to install_xtuple.sh helps CI

database/source/xt/functions/co_subtotal.sql
Stop including cancelled line items in the subtotal. Subtotal should
match how the QT client defines subtotal.
=> ISSUE 25588

foundation-database/public/trigger_functions/bomhead.sql
Consider in conjunction with xtuple/qt-client#663
=> Issue #25707: Routing BOM ChangeLog comments

foundation-database/public/tables/metasql/distributeInventory-locations.mql
required by xtuple/qt-client#664
=> Issue #25702: Add Zone filtering in Inventory Distribution screen

database/orm/models/customer.json, database/orm/models/invoice.json, database/source/xm/javascript/sales.sql, database/source/xt/tables/objtype.sql, enyo-client/application/source/en/strings.js, enyo-client/application/source/models/invoice.js, enyo-client/application/source/models/sales_order.js, enyo-client/application/source/views/list.js, enyo-client/application/source/views/workspace.js, enyo-client/extensions/source/billing/database/source/xm/javascript/billing.sql, enyo-client/extensions/source/purchasing/client/models/purchase_order.js, lib/backbone-x/source/model.js, lib/backbone-x/source/model_mixin.js, lib/enyo-x/source/views/list.js, lib/enyo-x/source/views/workspace.js, lib/orm/source/xm/javascript/model.sql, lib/orm/source/xt/javascript/data.sql, node-datasource/routes/generate_report.js
*https://github.com/xtuple/private-extensions/pull/592 should be pulled in private-extensions for UAT.
UAT is basically, print:
- `Sales Order` (list and workspace) - printing from list to PDF printer was printing 12 copies.
- `Purchase Order` (list and workspace) 
- `Purchase Order` (list and workspace)
- `Invoice` (list and workspace)
- `Enter Receipt` label (list and workspace)
- `Issue to Shipping` label (list and workspace)
- `Ship Shipment` (list and workspace)
- ~~`Lot/Serial/Relocate` label~~ **TODO**
- ~~`Issue to Manufacturing` label (list and workspace)~~ *see https://github.com/xtuple/xtuple/issues/2217*
- ~~`Work Order` (list and workspace)~~ **TODO**
- ~~`Returns/Credit Memo` (list and workspace)~~  **TODO**
...then add a printer, in my case I setup a CUPS PDF printer, add …
=> Print to OpenRPT

lib/enyo-x/source/views/transaction_list.js
UPC-A barcodes contain a `checksum` digit at the end of the barcode, if we just look at the first part of the input scan (matching the length of the upc/barcode) they should match.
=> resolves issue #1982

foundation-database/manifest.js, foundation-database/public/functions/deletecharacteristic.sql, foundation-database/public/patches/populate_charuse.sql, foundation-database/public/patches/populate_source.sql, foundation-database/public/tables/char.sql, foundation-database/public/tables/charuse.sql, foundation-database/public/tables/metasql/backlog-detail.mql
This is the basic server-side code to support characteristic association with arbitrary document types. Merge with the corresponding qt-client pull request xtuple/qt-client#692
=> issue #25741 - extension char assoc

foundation-database/public/tables/metasql/itemSources-detail.mql
Add Vendor Number to Item Sources display and mql
=> i25850_add_vendor_number

foundation-database/public/functions/explodewo.sql
I'm going for the world record for smallest bugfix with this PR.
Consider together with private-extensions PR #608
=> Issue #25827: Fix incorrect throughput calculations on alternate Prod UoM

lib/enyo-x/source/views/list.js, lib/enyo-x/source/views/workspace.js
This resolves T-CI failing in private-extensions
=> Add a guard clause in print function

foundation-database/public/tables/metasql/itemSites-detail.mql
Minor tweak to parameters to assist with lot/serial/location project
=> Issue #25914: Add Loc Ctrl parameter to ItemSites screen

enyo-client/application/source/en/strings.js, enyo-client/application/source/models/form.js, enyo-client/application/source/models/invoice.js, enyo-client/application/source/models/printer.js, enyo-client/application/source/models/sales_order.js, enyo-client/application/source/views/list.js, enyo-client/application/source/views/workspace.js, enyo-client/extensions/source/purchasing/client/models/purchase_order.js, lib/enyo-x/source/views/list.js, lib/enyo-x/source/views/transaction_list.js, lib/enyo-x/source/views/workspace.js, lib/orm/source/xm/javascript/model.sql, node-datasource/routes/generate_report.js
Also resolves:
> Printing (route) crappy error on print: "isError: true"
Print actions in UI all work:
- Sales > Sales Order List > Print Sales Order Form
- Sales > Sales Order List > Print PickList
- Sales > action gear at top > Print Sales Order Form
- Manufacturing > Work Order List > Print Work Order Form
- Manufacturing > Work Order List > Print Work Order Traveler
- Manufacturing > action gear at top > Print Work Order Form
- Manufacturing > action gear at top > Print Work Order Traveler
- Billing > Invoice List > Print
- Inventory > Issue to Shipping > tap an item, select Issue Stock > Print Label on save checkbox
- Inventory > Issue to Shipping > Print Label
- Inventory > Enter Receipt > tap an item, select Enter Receipt > Print Label on save checkbox
- Inventory > Enter Receipt > …
=> Print corrections

enyo-client/application/source/en/strings.js, lib/enyo-x/source/views/transaction_list.js
Bare minimum changes here to address 2 bugs.
1. dogfood issue # 26027
2. If the item had blank barcode it was accepting item scan
=> resolves issue #26027: scanning bugs

foundation-database/public/functions/cntctmerge.sql, foundation-database/public/functions/cntctselect.sql, foundation-database/public/functions/saveimageass.sql, foundation-database/public/functions/saveitemimage.sql
Queried using:   grep -irn "INSERT INTO .\{1,10\} values" .
=> Issue #24727: remove blind inserts

foundation-database/public/trigger_functions/item.sql
Item UoM conversion checks previously written for xDrupal.  Moved from that package to xTuple core
=> Issue #23019: Move Item UoM conversion checks to xTuple core

foundation-database/public/tables/report/ShippingLabelsBySO.xml, lib/enyo-x/source/views/list.js, lib/enyo-x/source/views/workspace.js, node-datasource/routes/generate_report.js
UAT:
*be sure `Xvfb` is running -  `sudo Xvfb :17`
Print shipping labels:
1. Create a Sales Order with multiple line items
2. Issue to Shipping in mobile, select a line item, Issue Stock, enter qty, check Print Label box, Issue. A new tab should open with the ShippingLabelsBySo report printed as pdf for that line item.
3. Test printing in qt-client: Inventory > Shipping > Forms > Shipping Labels > ...by SO. This should print _all_ the line item's labels.
=> ShippingLabelsBySo add new var, minor correction to list and ws print methods 

foundation-database/manifest.js, foundation-database/public/tables/report/APOpenItem.xml
=> Issue #25963: AP Open Item report

foundation-database/api/views/currencyrate.sql, foundation-database/manifest.js
@gilmoskowitz This meets the requirement as specified in the last comment on the issue.
Not sure if we want to do more??  I know @davidbeauchamp has done a funky exchange rate import script using some FX webservice.  I think it is currently used in dogfood.
I have left the issue marked as open (unresolved) at the moment until we decide if anything else is required.
=> Issue #20129: Currency Exchange Rate interface

lib/orm/source/xm/javascript/model.sql, lib/orm/source/xt/javascript/data.sql, node-datasource/main.js, scripts/lib/util/process_manifest.js
backports https://github.com/xtuple/xtuple/pull/2406
=> Misc rest 49x

lib/enyo-x/source/widgets/date.js
=> set min-width to 300px for datePicker widget, is this the right fix?

foundation-database/public/indexes/recv.sql
Issue directly solve here: xtuple/xtuple#2422
Core app changes at xtuple/qt-client#797
=> Issue #25762: Database performance improvement

foundation-database/public/functions/postglseriesnosumm.sql
Return meaningful message when posting to non-existant period
=> Issue #25686: Resolve meaningless error msg when posting GL Series

foundation-database/manifest.js, foundation-database/public/functions/enterporeturn.sql, foundation-database/public/tables/poreject.sql, foundation-database/public/tables/report/UnpostedReturnsForPO.xml
Add Vendor Return Authorisation to PO Return documentation
=> Issue 24158: Add RMA field to PO Returns

foundation-database/public/patches/fixaccntname.sql, foundation-database/public/patches/fixflcol.sql, foundation-database/public/tables/itemsite.sql, foundation-database/public/tables/location.sql, foundation-database/public/types/itemprice.sql
See comments below. Those are the only changes in this PR. The rest is a merge forward. `4_10_x` now builds on existing databases.
=> Merge forward 4_9_x to 4_10_x. Fix build_app errors on existing databases.

database/source/xt/trigger_functions/acttype_did_change.sql
Removed an unnecessary coalesce from the trigger that creates the view.
=> resolves df incident #26446 : create/replace xt.act error

database/orm/models/customer.json, enyo-client/application/source/models/customer.js, enyo-client/application/source/widgets/parameter.js
https://github.com/xtuple/xtuple/issues/1963
=> resolves issue #1963 - add char to cust list

lib/enyo-x/source/views/grid_box.js
https://github.com/xtuple/xtuple/issues/1860
=> resolves issue #1860 - parent, child save ws error

foundation-database/public/trigger_functions/trialbal.sql
Fix single company SQL array error
=> Correct trialbal trigger function array error when only single company

scripts/lib/util/process_manifest.js
see https://github.com/xtuple/xtuple/pull/2519#issuecomment-147242434 for motivation
=> try to make manifest processing errors easier to find in ci output

foundation-database/public/functions/postporeturns.sql
G/L postings had incorrectly reversed Dr and Cr
=> Issue #26757: Fix PO Returns Purchase Liability G/L Posting error

foundation-database/manifest.js
Fix missing entry from manifest file
=> Issue #26751 Tax Return report

foundation-database/public/functions/updateabcclass.sql, foundation-database/public/tables/metasql/inventoryAvailability-general.mql, foundation-database/public/tables/metasql/inventoryHistory-detail.mql, foundation-database/public/tables/metasql/qoh-detail.mql, foundation-database/public/tables/metasql/usageStatistics-detail.mql
Resolve timing issue with ABC calculation.   Plus add ABC filtering into various lists
=> Issue #26741 and issue #2583: ABC Classification fix and additional reporting

foundation-database/public/tables/metasql/packingListBatch-detail.mql
Filter Packing List Batch by Hold Status - also display Pack Date (sortable)
=> Issue #26246: Add Pack Date and selectable Hold Status to Packing List Batch

foundation-database/public/functions/summtransr.sql
Altered underlying function so may well fix other things that use this function.
=> Issue #26848: Add missing RR transaction to Usage Statistics report

foundation-database/public/tables/metasql/shipments-detail.mql
Change the Metasql for the line number
=> Issue 26841 shipment by shipment Metagsql change

foundation-database/public/tables/metasql/shipments-detail.mql
followup commit to fix CI failures on #2541
=> issue #26841 - followup - rm byte-order mark to help build_app and updater

foundation-database/public/trigger_functions/poitem.sql
Found PO Quick Item was not handling taxation at all.   This resolves problem for Inventory Items but not for non-Inventory Expense items.   A permanent resolution requires a rewrite of the poItemTable Model/View logic to add Tax Type to the quick entry screen.
=> Issue #26976: PO Item refresh & taxation issues

foundation-database/manifest.js, foundation-database/public/functions/convertquote.sql, foundation-database/public/functions/convertquotetoinvoice.sql, foundation-database/public/patches/populate_evnttype.sql
=> Issue #8983: Add Converted Quote event

foundation-database/api/views/itemsite.sql, foundation-database/public/functions/getitemsiteid.sql
This resulted in a 260x performance improvement in testing
=> Issue #25441: api.itemsite Update performance

foundation-database/public/tables/metasql/opensalesorders-detail.mql, foundation-database/public/tables/metasql/salesOrders-detail.mql
=> Issue #26699: Additional Sales Order list/search filters

foundation-database/public/functions/fixacl.sql
Could cause issues with autoupdater or scripted update
=> Issue #26477: Remedy fixACL function error message

foundation-database/public/tables/metasql/package-items.mql
This change only works after with Updater 2.3.0
=> Issue #27066: Add support for Materialized Views

foundation-database/public/tables/metasql/creditMemoCreditCards-detail.mql
This pull request has a corresponding pull request in qt-client.  The two pull requests should be tested together.
=> issue #26638 Added selection of cohead_id (if present) to creditMemoCreditCards-detail.mql

foundation-database/public/tables/report/APAging.xml, foundation-database/public/tables/report/APAgingSummary.xml
Fix field defn problem, labels and layout
=> issue #26375 - Resolve minor AP Aging report issues

foundation-database/manifest.js, foundation-database/public/tables/metasql/images-list.mql
Convert Images list to metasql.  Two examples exist in the metasql which calculate or don't calculate image size.  The perofrmance difference in reference Db was 45 seconds -> 1 second.
=> Issue #27365:  Images List metasql

foundation-database/public/functions/itemuomtouom.sql, foundation-database/public/functions/itemuomtouomratio.sql
Provide meaningful Item Number and UoM text rather than internal ids.
=> Provide more user-friendly error message on UoM conversion errors

node-datasource/main.js
Internal vs External hostname setting was not working - so switched to manual setting of these metrics
=> Issue #27407: Move Webapp metric from Automatic determination to manual

foundation-database/public/tables/metasql/creditMemoCreditCards-detail.mql
Accompanies xtuple/qt-client#1091
=> issue #26638 - backport to 4.9.3

foundation-database/manifest.js, foundation-database/public/functions/issueallbalancetoshipping.sql, foundation-database/public/functions/issuelinebalancetoshipping.sql, foundation-database/public/functions/issuetoshipping.sql, foundation-database/public/functions/qtylocation.sql, foundation-database/public/functions/qtyreserved.sql, foundation-database/public/tables/coitem.sql, foundation-database/public/tables/metasql/inventoryAvailability-byCustOrSO.mql, foundation-database/public/tables/metasql/reservations-detail.mql
requires xtuple/qt-client#1093
=> issue #26687 - backport to 4.9.3

foundation-database/public/functions/copyitemsite.sql
accompanies xtuple/qt-client#1098
=> issue #26705 - backport to 4.9.3

foundation-database/manifest.js, foundation-database/public/functions/_docinfo.sql, foundation-database/public/functions/_gettargetdocument.sql, foundation-database/public/types/_targetdoc.sql, foundation-database/public/views/docinfo.sql, test/database/docinfo.js
requires xtuple/qt-client#1101
=> issue #26887 - backport to 4.9.3

foundation-database/public/tables/metasql/incidents-detail.mql
requires xtuple/qt-client#1102
=> bug #27105 - backport to 4.9.3

foundation-database/public/functions/copyaccountingyearperiod.sql, foundation-database/public/functions/createaccountingperiod.sql
If we are doing a 4.9.3 it would be nice to backport these fixes to that.
=> Issue #27205 Additional trial balance checks.  Resolve ordering issues

foundation-database/public/functions/postproduction.sql
Modify Post Production Function to process user defined cost elements on
Average costed items
=> issue #27445 - Cost Elements on Average Costed items

foundation-database/public/tables/metasql/itemCost-detail.mql
=> issue #27362 - cherry-pick mccjim's .mql to address travis-ci failure

foundation-database/public/trigger_functions/coitem.sql
I made two trigger changes in order to have characteristics written to
sales order lines consistently when orders are created from the client
and the internet.  You will find the initials "rks" with comments in the
areas where the changes were made.
=> issue #27331 - characteristics on internet order sales line items

foundation-database/manifest.js, foundation-database/public/functions/saveaddr.sql, foundation-database/public/patches/fixaddress.sql, foundation-database/public/trigger_functions/cmhead.sql, foundation-database/public/trigger_functions/cohead.sql, foundation-database/public/trigger_functions/invchead.sql, foundation-database/public/trigger_functions/pohead.sql, foundation-database/public/trigger_functions/quhead.sql, test/database/functions/saveaddr.js
replaces https://github.com/xtuple/xtuple/pull/2643
paired with https://github.com/xtuple/private-extensions/pull/746
The additions to the trigger functions allow the web client to run. The web client stack works through views which appear to interfere with table-level column defaults.
=> issue #25871 - alter address columns to not null with default

foundation-database/manifest.js, foundation-database/public/functions/calculatetaxhist.sql, foundation-database/public/functions/updatememotax.sql, foundation-database/public/functions/updatemiscvouchertax.sql, foundation-database/public/tables/metasql/taxHistory-detail.mql, foundation-database/public/tables/metasql/taxReturn-detail.mql, foundation-database/public/tables/tax.sql, foundation-database/public/tables/taxass.sql, foundation-database/public/tables/taxhist.sql, foundation-database/public/trigger_functions/vodist.sql
Tidy up AR/AP Memo approach. 
#27338: European VAT Reverse Charges functionality
=> Issue #27338: VAT Taxation enhancements (incl. reverse charges)

foundation-database/public/tables/metasql/currencyConversions-detail.mql, foundation-database/public/trigger_functions/curr_rate.sql
Minor tweak of currency display to 6 dp.
Resolve bug in exchange rate trigger
=> Issue #24549: Resolve some currency conversion issues

foundation-database/public/functions/postproduction.sql
replaces https://github.com/xtuple/xtuple/pull/2657
=> issue #27700 - fix how postproduction handles lower-level costs

foundation-database/public/functions/calculatetaxdetailsummary.sql, foundation-database/public/functions/calculatetaxhist.sql, foundation-database/public/tables/metasql/taxHistory-detail.mql
Improve handling of VAT reverse charges for PO Vouchers and the Tax History report
=> Issue #27338: Further VAT bugfixes (reverse charge issues)

foundation-database/public/functions/explodewo.sql
Copies WO characteristics from parent to child when exploding
=> Issue #27366: W/O specific characteristics

foundation-database/public/patches/fixaddress.sql
These changes improve performance of this step of the upgrade by ~10^3 in one customer database.
~~Do not merge until @xtpclark has a chance to test in another.~~ Test in a large customer database where this was initially observed shows significant performance improvement: failure after 8 hours is now success after 25 min.
=> issue #27777 - combine updates and disable triggers

foundation-database/manifest.js, foundation-database/public/tables/metasql/voucher-miscDistr.mql, foundation-database/public/tables/metasql/voucher-poitems.mql
=> Issue #27780: Convert Voucher code to utilise metaSQL

database/source/xm/javascript/credit_card.sql, lib/orm/source/xt/javascript/rest.sql
=> Add dispatch function/service to save credit cards over the REST API.

database/source/xm/javascript/credit_card.sql, database/source/xm/javascript/customer.sql, lib/orm/source/xt/javascript/rest.sql
This PR also includes a `git cherry-pick` of https://github.com/xtuple/xtuple/pull/2678 for 4_10_x.
=> Return new itemipsprice() data to include list, discount and sale price.

bower.json, database/source/update_version.sql, foundation-database/public/tables/setVersion.sql, npm-shrinkwrap.json, package.json, scripts/xml/distribution_install.xml, scripts/xml/distribution_package.xml, scripts/xml/ent_install.xml, scripts/xml/ent_package.xml, scripts/xml/postbooks_package.xml, scripts/xml/xtmfg_install.xml, scripts/xml/xtmfg_install_to_dist.xml, scripts/xml/xtmfg_package.xml
=> Updated version numbers

scripts/lib/build_client.js, scripts/lib/orm.js, scripts/lib/util/convert_specialized.js, scripts/lib/util/process_manifest.js
I ran into some issues adding files that also contained `$$`. This change should prevent that.
=> Namespace posgres double dollar sign quotes so they don't clash with wrapped file contents.

foundation-database/public/functions/copyproject.sql
Project Type already being copied.
=> Issue #27716: Copy Project function - include TE billing in copy

foundation-database/public/tables/metasql/timePhasedSales-detail.mql
Convert metaSQL to use the consistent salehistory views
=> Issue #27584: Time Phased Sales inconsistent with other sales reports

foundation-database/public/functions/calculatetaxdetailsummary.sql, foundation-database/public/functions/updatemiscvouchertax.sql, foundation-database/public/tables/metasql/taxHistory-detail.mql, foundation-database/public/trigger_functions/vodist.sql
plus minor improvements based on beta testing feedback
requires xtuple/xtuple#2718
=> Issue #28027: Resolve VAT issues in Tax History report

foundation-database/public/functions/copyso.sql
Fix costing on SO copy for when metric "wholesalepricecosting" is set.
=> Issue 28081

foundation-database/manifest.js, foundation-database/public/functions/checklocation.sql, foundation-database/public/functions/deletelocation.sql, foundation-database/public/functions/validlocation.sql, foundation-database/public/tables/location.sql
=> Issue #20423: Deactivate locations

foundation-database/public/functions/postcheck.sql, foundation-database/public/functions/reversecashreceipt.sql, foundation-database/public/functions/voidpostedcheck.sql
Reversal Transactions - Taxation handling for reversal of Misc Payment and Misc Cash Receipts
=> Issue #28236: Taxation handling for Reversal transactions 

foundation-database/public/tables/metasql/itemSources-prices.mql
Conflict between uses of metaSQL in different areas of the application.
=> Could not view/edit prices on inactive Item Source

foundation-database/manifest.js, foundation-database/public/functions/getedition.sql, test/database/functions/getedition.js
goes along with changes to [qt-client](https://github.com/xtuple/qt-client/pull/1343), [private-extensions](https://github.com/xtuple/private-extensions/pull/821), and [xtdesktop](https://github.com/xtuple/xtdesktop/pull/61) repositories
=> issue #28306 - common edition infrastructure

foundation-database/public/functions/getcompanyid.sql
Function assumes company is a integer value instead of alphanumeric
=> Issue #28408: Correct data type bug in getcompanyid function

foundation-database/public/functions/updatememotax.sql, foundation-database/public/functions/voidapopenvoucher.sql, foundation-database/public/tables/metasql/taxHistory-detail.mql, foundation-database/public/tables/metasql/taxReturn-detail.mql
Also resolves bug in Tax Return report found in testing.
~~NO NOT MERGE YET:  Unit testing completed, but I need to retest on a clean build~~
Tested on clean build and various scenarios are now displaying correctly on Tax History and Tax Return reports
=> Issue #28359: Resolve tax issues on voiding Vouchers

foundation-database/public/trigger_functions/charass.sql
as these characteristics are required to be retained for traceability purposes
=> Issue #27761: Exclude Lot Serial characteristics from unique checks

lib/orm/source/xt/javascript/data.sql
One of the goals of the REST API is for clients to only make one POST and all actions to trigger automatically. REST clients shouldn't need to know they also have to create a work order. 
The `Product Configurator` feature in xTuple's Qt Client uses line item chars to create Work Orders. Through the `XM.SalesOrder` ORM, all data can be pushed into database, but the `coitem` records go in before the `charass` records. Therefore, the `_soitemBeforeTrigger()` call to `createwo()` won't work.
With this change to `XT.Data.createRecord()`, after an insert to the parent table (`cohead` then `coitem`), the child ORMs like `Characteristic` are inserted. Then, once the data is there, I do a simple `UPDATE public.coitem SET obj_uuid= obj_uuid WHERE coitem_id = $1` to cause any update triggers to …
=> Redmine #3096 Add ability for REST API to trigger Product Configurator Work Order Creation

lib/module/rjson, scripts/install_xtuple.sh
caused by accidental rm of rjson
=> issue #28474, issue #24329 - fix build problems

foundation-database/public/functions/splitreceipt.sql
and fixed split receipt freight functionality
=> issue #28280 - removed transaction block from voucherItem

foundation-database/public/tables/metasql/taxBreakdown-detail.mql
=> Issue 28456: Resolve some residual VAT Taxation bugs, features and

foundation-database/public/tables/metasql/timePhasedSales-detail.mql, foundation-database/public/views/saleshistory.sql, foundation-database/public/views/saleshistorymisc.sql
(cherry picked from commit 724a2f4b4b6069ba28c587e02216d001e3a85ca2)
=> issue #28547 - add uom join

foundation-database/public/functions/voidapopenvoucher.sql
Changes test for open vouchers as reported on issue 28582
=> issue #28582 - Update voidapvoucher

.travis.yml, foundation-database/public/tables/metasql/gltransactions-detail.mql
(cherry picked from commit f91d0f401237c7028b1cab01467ccdcd911e287c)
=> issue #28599 - Fixed mismatched parentheses

foundation-database/public/functions/postinvtrans.sql
cherry picked commits cc8d57b, a9dd545, fb81957
=> issue #28634 - prevent negative inventory if user requested that

foundation-database/public/tables/report/UnpostedReturnsForPO.xml
(cherry picked from commit 339ca14ca9395a4c95bf38ab78f9b634c4d0cc94)
=> issue #28604 - Fixed typo

foundation-database/public/functions/cntctdups.sql, foundation-database/public/types/cntctdup.sql, test/database/functions/cntctdups.js
and simplify substantially by using metasql
=> issue #28289 - make selects match cntctdup type

foundation-database/public/functions/postinvoice.sql
(cherry picked from commit 9f13553b2747374d8d2090db56dd8132cbb89044)
=> issue #28774 - backport fix - select necessary column

foundation-database/public/trigger_functions/coitem.sql
(cherry picked from commit 8c767b2316cffa251958931b442e035047b2264a)
=> issue #28446 - backport - prevent circular triggers

foundation-database/manifest.js, foundation-database/public/tables/comment.sql
(cherry picked from commit 0a5e3bf1cfd837364f4842f74f1395fbf36edd3c)
+ add to manifest.js
=> issue #25638 - backport - Add indices

lib/orm/source/xt/javascript/parsemetasql.sql, lib/orm/source/xt/pegs/metasql.peg
(cherry picked from commits 501e139 60c754c)
=> issue #28714 - backport - reduce whitespace sensitivity

foundation-database/public/functions/returnshipmenttransaction.sql
(cherry picked from commits 0e4b19e 671430a)
=> issue #28657 - backport - update freight on return shipment

foundation-database/public/tables/metasql/qoh-detail.mql
Resolves multi warehouse issue in Postbooks databases
=> Issue #28843: Postbooks error in QOH By Location report due to multiwhs

database/source/xt/functions/createwf.sql, enyo-client/application/source/models/sales_order.js, lib/backbone-x/source/characteristic.js, test/specs/sales_order.js
Will have a merge conflict with https://github.com/xtuple/xtuple/pull/2877 after that's been merged.
=> Fix XM.SalesOrder workflow test for pri-ext with metric 'TriggerWorkflow' on.

foundation-database/public/functions/woplancost.sql, foundation-database/public/tables/metasql/workOrderSchedule-detail.mql
Supporting files for dsowoschedule
=> issue #28730 - add wip value to wip schedule

foundation-database/public/tables/bankrecitem.sql
=> Issue #28170: Bank Rec add foreign key to prevent orphaned records

foundation-database/public/functions/postinvtrans.sql
(cherry picked from commit e73cefb101401ae184e202b2516da0eaada6b94b)
=> issue #28634 - backport - use unique error code

foundation-database/public/tables/metasql/invoiceItems-list.mql
Tested with Sales Order invoices and Misc. Invoices.   With and without Price UOMs
=> Issue #25077: Revise Invoice Item margin to handle different Price Uoms

foundation-database/public/tables/metasql/itemPricingSchedule-detail.mql
(cherry picked from commit ee8d71e98240e121b08df1def1c22e4e87af06af)
=> Issue #28850: Resolve display of Freight Pricing Schedule items

foundation-database/api/views/purchaseline.sql, foundation-database/api/views/purchaselinechar.sql, foundation-database/api/views/quotelinechar.sql, foundation-database/api/views/saleslinechar.sql, foundation-database/public/functions/convertquote.sql, foundation-database/public/functions/copyquotetocustomer.sql, foundation-database/public/functions/releasepr.sql, foundation-database/public/functions/updatecharassignment.sql, foundation-database/public/trigger_functions/coitem.sql
Only propagate to order item chars if selected in characteristic setup.
=> Issue #27705: Resolve Item characteristic propagation to order documents

foundation-database/public/functions/calcinvoiceamt.sql, foundation-database/public/tables/metasql/invoiceItems-list.mql, foundation-database/public/tables/metasql/invoices-detail.mql
Reuse calcinvoiceamt() function in both places to ensure consistency.
Also added margin on unposted invoices screen to clarify values.
=> Issue #25077: Resolve margin issues and discrepancies on Invoice Item

foundation-database/manifest.js, foundation-database/public/tables/metasql/customer-lastYearSales.mql, foundation-database/public/tables/metasql/customer-ytdSales.mql
Resolve sales history on customer workbench, plus switch to metaSQL
to allow alternate sales history calculations (i.e. fiscal year)
=> Issue #27500: Customer Sales History

foundation-database/public/tables/report/WarehouseLocationMasterList.xml
plus resolve missing zone filters
requires xtuple/qt-client#1470
=> Issue #28020: Resolve discrepancy in Location report 

database/source/xt/functions/createwf.sql
@rkannadevara - please try to reproduce bug 28896 with this updated version of the `createwf()` function. It should give more information that may help find the real source of the bug.
=> issue #28896 - allow for extensions defining their own wftypes

foundation-database/public/tables/metasql/poItems-list.mql
description in the Purchase Order items list
=> Issue #29074: Resolve display of non-inventory items with a Vendor

foundation-database/public/tables/report/GLTransactions.xml
When Opening balances are selected
=> Issue #29173: Resolve erroneous sort order in GL Transactions report 

foundation-database/public/tables/char.sql
=> Issue #28606 Characteristic enhancements

foundation-database/public/functions/deletewo.sql
plus convert error messaging to new method
=> Issue #28546: Prevent deletion of WO if WIP on the order

foundation-database/public/tables/metasql/ledgercontrol-detail.mql
3 fixes to query:
1. apopen should be stated in base currency
2. univoiced receipts was missing value of returns
3. for inventory average costed items were not being costed.
=> issue #29330 - Ledger control metasql

foundation-database/manifest.js
Caused by missing manifest entry for table changes in xtuple/xtuple#2923
=> Issue #29293: Resolve inability to void Voucher. 

foundation-database/public/trigger_functions/poitem.sql
Replaced this logic with tax type handling in the PO Item Quick Entry view
=> Issue #29274 Purchase Item Tax Type handling

foundation-database/create_notifications.sql, foundation-database/manifest.js
required by xtuple/qt-client#1520
=> issue #9241 - create triggers for refreshing client-side caches

foundation-database/manifest.js, foundation-database/public/tables/report/itemLabel.xml
=> issue #29592 - add a sample item label report

foundation-database/public/functions/copyso.sql, foundation-database/public/functions/editccnumber.sql, foundation-database/public/functions/insertccard.sql
New MasterCard BIN ranges for 2017. Check full BIN instead of first 2 digits.
=> Issue #29633 MasterCard BIN Ranges

foundation-database/public/functions/updatestdcost.sql
This was a timing issue with calculating Std Cost.  Also affected the GL postings and Inventory History (not mentioned in original issue).
=> Issue #29408: Deleting Std cost did not update itemsite or history

foundation-database/public/tables/metasql/arOpenItems-detail.mql, foundation-database/public/tables/metasql/arOpenItems-f_detail.mql
Added the same field logic to the formatted query but not to the report as I have left this to individual customers to decide if needed.
=> Issue #28773: Add Customer PO to Open Receivables

foundation-database/api/views/vendorcomment.sql, foundation-database/manifest.js
=> Issue #28925: Contributed API vendor comments

foundation-database/api/views/itemsite.sql
=> Issue #29359: Correct api.itemsite INSERT RULE

database/source/xt/functions/createwf.sql
29746 is a duplicate of 28896 and 29133 is a regression
from the fix to 28896. This commit pulls the 4_11_x version
of createwf back to 4_10_x.
=> issue #28896, issue #29133 - backport to 4.10.1 to fix issue #29746

foundation-database/public/patches/populate_fundstype.sql
Found this error when testing Card on File integrations.
=> It's MasterCard, not Master Card

scripts/lib/build_client.js
Choose a feature of core code that distinguishes it
instead of assuming anything about the directory path
in which the core has been checked out.
=> switching to jenkins revealed a false assumption

foundation-database/public/patches/populate_charuse.sql
=> issue #29827 - best effort at creating new charuse for line items

foundation-database/manifest.js, foundation-database/public/tables/classcodetax.sql
This can wait till 4.12 if desired
=> Issue #29702: Default Item Tax Types

foundation-database/public/tables/potype.sql
Some databases seem to have the potype table with both old and new columns defined.
=> issue #30280, issue #30214 - expand the range of corner cases handled

foundation-database/manifest.js, foundation-database/public/functions/postproduction.sql, foundation-database/public/patches/evnttype.sql
convert reporting a hard error to logging an event notification.
this allows backflushing operations to work as before.
=> issue #30283 - allow posting mixed production & operations

scripts/release_build.sh
https://github.com/xtuple/nodejsshim/pull/16
https://github.com/xtuple/xtdash/pull/38
=> Use correct foundation-database path so build_app works.

foundation-database/public/functions/insertgltransaction.sql
=> Issue 29720: Credit Memo post to GL even when metric set to false

foundation-database/public/patches/populate_ccpay_card_type.sql
not technically part of the original request but this change improves
performance of the ccpay table upgrade by about 50%, which should
turn into a performance improvement of overall upgrade by about 5%.
=> issue #30186 - improve perf of ccpay table patch

foundation-database/public/patches/fixaccntname.sql
=> Issue #30538: GL Account name is being blanked out

foundation-database/public/tables/recur.sql
=> Issue #30537: Remove recur constraint as it was preventing creation

foundation-database/manifest.js, lib/orm/source/create_plv8.sql
cherry-pick d6ebcc57619b81b45fdb51632f292c61884860df 2e2a49323dba4046a150d2a79a4619f7120a0f01
=> backport fixes to plv8 init function forward reference

foundation-database/public/tables/metasql/salesOrderItems-list.mql
This PR resolves stated issue, but there are a few other problems with aliases found during testing, possibly not documented in issues.
=> Issue #30391: Duplicate SO Items lines when similar alias codes are in system

foundation-database/public/functions/createinvoice.sql, foundation-database/public/patches/populate_source.sql, foundation-database/public/tables/metasql/returnAuthorizations-lookupDetail.mql, foundation-database/public/trigger_functions/charass.sql
resolves issues #5043, #27331, #19111, #28159
=> issue #5043, issue #27331, issue #19111, issue #28159 - Characteristics minor refactor

foundation-database/public/functions/voidinvoice.sql
works in conjunction with client-side change
alternative to xtuple/qt-client#1766
=> issue #29873 - allow specifying the voiding date

scripts/UpgradeTest.sh, scripts/release_build.sh, scripts/xml/add-manufacturing-to-distribution.xml, scripts/xml/distribution-install.xml, scripts/xml/distribution-upgrade.xml, scripts/xml/enterprise-install.xml, scripts/xml/enterprise-upgrade.xml, scripts/xml/manufacturing-install.xml, scripts/xml/manufacturing-upgrade.xml, scripts/xml/postbooks-upgrade.xml, scripts/xml/shared.xml
tested with 4.4.0, 4.5.0, 4.6.0, 4.8.1, 4.9.0 -> 4.11.1
=> issue #31053 - added upgrade test, standardized upgrade internal dir names

foundation-database/public/trigger_functions/invchead.sql, foundation-database/public/trigger_functions/invcitem.sql, foundation-database/public/trigger_functions/vohead.sql
Initial commit records creation only.  Waiting on feedback regarding automatic change recording.
=> Issue #30948: Add comments to vouchers and invoices

foundation-database/api/views/custshipto.sql, foundation-database/api/views/vendor.sql
Also resolves #30894 Cust Ship To API view
=> Issue #30911, issue #30894: Add CRM account as default for empty Vendor number in API

foundation-database/public/tables/metasql/contacts-detail.mql
https://github.com/xtuple/qt-client/pull/1831
=> issue #31217 - support for contact list prospect actions in contacts list

foundation-database/manifest.js, foundation-database/public/tables/metasql/documents-list.mql
Needed by  https://github.com/xtuple/qt-client/pull/1836
=> Fixes #31445 - Add documents-list MetaSQL to support documents scriping

foundation-database/public/tables/metasql/vendorAPHistory-detail.mql, foundation-database/public/tables/report/VendorAPHistory.xml
also reduced redundancy to focus on the important
differences in the various parts of the union
=> issue #31730 - handle vendor group instead of cluster

foundation-database/empty_data.sql, foundation-database/quickstart_data.sql, test/database/bankrec.js, test/database/dblib.js, test/database/functions/araging.js
also added and tested convenience function to dblib to use js metasql parser
this should fix the CI failures on xtuple/xtuple#3212 and xtuple/xtuple#3213
=> fix various beginning-of-year problems

foundation-database/public/functions/postinvtrans.sql, test/database/functions/correctporeceipt.js, test/database/functions/correctproduction.js, test/database/functions/issuetoshipping.js, test/database/functions/issuewomaterial.js, test/database/functions/postcreditmemo.js, test/database/functions/postinvoice.js, test/database/functions/postporeturns.js, test/database/functions/postproduction.js, test/database/functions/postreceipt.js, test/database/functions/recallshipment.js, test/database/functions/returnshipmenttransaction.js, test/database/functions/returnwomaterial.js, test/database/functions/shipshipment.js, test/database/functions/voidcreditmemo.js, test/database/functions/voidinvoice.js
and update the tests to match.
Replaces xtuple/xtuple#3213
=> issue #31984 - revert unnecessary change

test/database/bankrec.js, test/database/dblib.js, test/database/functions/issuetoshipping.js, test/database/functions/recallshipment.js, test/database/functions/returnshipmenttransaction.js, test/database/functions/shipshipment.js
For https://github.com/xtuple/payment-gateways/pull/7
=> Make dbLib.createSalesOrder() more flexible.

enyo-client/extensions/source/billing/database/source/xt/tables/rptdef.sql, foundation-database/public/functions/numofdatabaseusers.sql, foundation-database/public/functions/numofserverusers.sql, foundation-database/public/functions/postdistdetail.sql, foundation-database/public/types/_targetdoc.sql
and simplify `numOfDatabaseUsers()`
=> remove byte order marks, add 2018 fiscal year to demo db

enyo-client/application/source/en/strings.js, enyo-client/application/source/models/sales_order_base.js, enyo-client/application/source/models/static.js, foundation-database/api/views/salesorder.sql, foundation-database/public/functions/issuetoshipping.sql, foundation-database/public/functions/shipshipment.sql, foundation-database/public/tables/metasql/opensalesorders-detail.mql, foundation-database/public/tables/metasql/packingListBatch-detail.mql, foundation-database/public/tables/metasql/partiallyShippedOrders-detail.mql, foundation-database/public/tables/metasql/summarizedBacklogByWarehouse-detail.mql, foundation-database/public/tables/report/PartiallyShippedOrders.xml, foundation-database/public/tables/report/SummarizedBacklogByWarehouse.xml, foundation-database/public/trigger_functions/cohead.sql
Associated with xtuple/qt-client#1868, xtuple/private-extensions#994, and xtuple/xdruple-extension#54.
=> Add Tax Hold Type

foundation-database/public/tables/metasql/orderActivityByProject-detail.mql, test/database/metasql/accountNumbers-detail.js, test/database/metasql/bom-detail.js, test/database/metasql/orderActivityByProject-detail.js
=> issue #31733 - don't show closed items by default

foundation-database/public/functions/itemcharprice.sql
Consolidate seven item char price queries into one following the `itemIpsPrice()` function's pattern.
=> Issue #33000 - Simplify and reduce itemCharPrice() queries.

foundation-database/public/functions/login.sql
Companion to https://github.com/xtuple/qt-client/pull/1933. This will work without it, but it won't work without this.
=> [11967] Add user preference to set time zone

foundation-database/public/functions/updatestdcost.sql, foundation-database/public/tables/invhist.sql
where no value change is posted.
=> [32307] Prevent spurious inventory history records for item cost changes

foundation-database/public/functions/createaccountingperiod.sql
=> [31858] Resolve missing names on generated Fiscal Accounting Periods

foundation-database/public/tables/metasql/customers-statement.mql
=> [25322] Fix errorneous results from Customer Statements

foundation-database/public/tables/cashrcpt.sql
related to #3302 and the fix for bug 32858
=> [33197] drop dependent views to fix build_app errs

foundation-database/public/functions/postcheck.sql, foundation-database/public/functions/postchecks.sql, test/database/bankrec.js, test/database/functions/voidpostedcheck.js
Notify user when no valid payments to post.
Additional checks on payment status.  Resolved latent sql bugs when posting payments.
=> [32113] Fix ability to post unprinted payments.  

foundation-database/public/functions/postvoucher.sql, foundation-database/public/patches/populate_source.sql, foundation-database/public/tables/metasql/voucher-miscDistr.mql
=> [30866] [30861] Landed Cost additional voucher cross-referencing. 

foundation-database/public/functions/enterreceipt.sql, foundation-database/public/tables/metasql/itemReceipt-populateEdit.mql, foundation-database/public/tables/metasql/itemReceipt-populateNew.mql
Also prevents amending an item type if the item site validation checks would fail
=> [33238] Prevent ability to receipt into inactive item sites.

foundation-database/manifest.js, foundation-database/public/functions/formatavataxpayload.sql, foundation-database/public/functions/formatexternaltaxcodes.sql, foundation-database/public/functions/saveavatax.sql, foundation-database/public/functions/savetax.sql
Tax Type configuration
CreateTransaction initial work 
CommitTransaction built (not plugged in yet or tested)
=> Avalara Integration

foundation-database/api/views/invoiceline.sql
Added invcitem_subnumber column to view and appropriate changes to insert and update.
=> issue #31801 : added subnumber column to view

foundation-database/api/views/site.sql
Gil make sure this looks good on your end. I think I messed it up the first time around.
Tom
=> [30893] api site sql

test/database/functions/addrusecount.js
For: https://github.com/xtuple/private-extensions/pull/1015
=> Increase timeout so tests pass?

foundation-database/api/views/invoiceline.sql, test/database/views/invoiceline.js
- Created `test/database/views/invoiceline.js` to test invoiceline view
- Added checks to see if record was found on insert and update functions.
=> issue #32336 - added checks to invoiceline.sql and created test for invoiceline view

foundation-database/public/functions/formatexternaltaxcodes.sql
For whatever reason Avalara gives some tax codes a parent tax code that itself does not exist, causing them to be missing from this tree. This hack adds them in as placeholders to fill out the tree and nests them under a top level code. Some of these missing parent codes are only 4 characters for some reason so it still looks awkward, but we have to work with what Avalara gives us.
=> Fix missing tax codes

foundation-database/public/tables/metasql/contacts-detail.mql
and incidentally problematic references to contact created and updated columns
=> fix 'mrkd_id must be in group-by' error

foundation-database/public/functions/deletecheck.sql
to ensure consistency with other payment types
=> [33431] Allow deletion of voided EFT payment even if printed

foundation-database/public/tables/metasql/addresses-detail.mql
Some of this is already in version 5.0 so we need to watch for conflicts when merging 4.12 into 5.0
=> [10370] Add Search and Filters to CRM Address List

foundation-database/public/functions/issuetoshipping.sql
This is not a pretty solution as it results in an additional Db call, but the dependencies in the flow of data due to Sales Reservations require shipitems to be created before reservations are processed, before we obtain the transaction value from inventory history.  Only at that point do we know what the shipitem value should be.
realted to xtuple/xtuple#3288
=> [33646] Resolve issue where Ship Shipment was not posting to the GL

foundation-database/public/functions/checkprivilege.sql
Made this change to make resolution of another issue a bit easier.
=> Upgrade checkPrivilege() function to handle multiple inputs

foundation-database/public/tables/emp.sql, foundation-database/public/trigger_functions/emp.sql
Had to remove the FK constraint as it does not work with images source from child package tables
=> [26036] Employee images hitting foreign key issue on inherited tables

foundation-database/public/functions/checkprivilege.sql
check for ALL privileges assigned.
=> Update checkprivilege function to handle superuser check and check ALL

foundation-database/public/tables/metasql/documents-detail.mql
=> [25092] Add ability to search documents by Assignment Notes

foundation-database/public/tables/metasql/distributeInventory-locations.mql
Plus lock down some lot options and other quality of life improvements
=> [33279] Resolve further lot/serial bugs on W/O post production.  

foundation-database/public/tables/urlinfo.sql
Script ran on my test system but might be missing appropriate data to fully test.
=> [25092] Resolve foreign key issue with urlinfo sequence update by deferring

foundation-database/public/tables/urlinfo.sql
Fixes CI test rebuild from `xdruple.urlinfo_ext` fkey.
=> [25092] Fix urlinfo fkey migration to file_id sequence

foundation-database/public/tables/report/ItemCostsByClassCode.xml
Added same tolerance found in screen metaSQL to the report SQL
=> [33936] Item Costs by Class Code - fix discrepancy between screen and report

foundation-database/public/functions/countNotNull.sql
Simple helper function to use in constraint checks. Accepts an anyarray and counts the number of non null elements.
=> adds countNotNull function

foundation-database/api/views/vendor.sql
Issue #34022 - correct foreign key in api.vendor - #31105 related
=> [34022], [31105] - correct foreign key api.vendor

foundation-database/public/trigger_functions/salesrep.sql
Trigger was returning an incorrect NEW (thought this would cause an error, but it was silent)
=> [34077] Resolve Sales Rep deletion

foundation-database/public/functions/itemipsprice.sql
resolve alternate selling UoM pricing issues.
Also resolves issue #33855
=> [32197] [33855] Resolve sales order item pricing issues with alternate uoms

foundation-database/public/tables/cntctsel.sql
Could not reproduce exact error in issue but found newly added contact fields were causing problems.  Contact merge works without SQL error after this update
=> [33969] Update Contact Merge for new contact fields

foundation-database/public/tables/metasql/cashReceipts-detail.mql
Fixes Customer Workbench and Cash Receipts displays.
=> [34078] Cash Receipts SQL Error with customer groups

foundation-database/public/tables/metasql/employees-detail.mql
related update to xtmfg metaSQL as well.
=> [34061] Resolve schema sql issues with employees list

foundation-database/public/trigger_functions/emp.sql
=> [34122] Fix saving of Employee when no image is selected

foundation-database/api/views/site.sql
(cherry picked from commit 10beaa426b1e82bc51d3441606ec201fe5230129)
=> [30893] api_site_sql needs to honor foreign keys

foundation-database/public/functions/copysoheader.sql
removed cohead_taxtype from copysoheader function
=> [34220] Error with cohead_taxtype when copying SO

foundation-database/public/tables/metasql/orderActivityByProject-detail.mql
Edited the metasql query to filter out voided invoices
=> [31867] TE Project Form Lists/Invoices Section Includes Voided Invoices

foundation-database/public/functions/postporeturns.sql
Per @mccjim 's suggested change.
Needs to be cherry-picked back to 4.12
=> [34203] Amend PO Return costs if the item is standard costed.  

foundation-database/public/functions/postporeturns.sql
Per Jim McC's suggested change
=> [34203] Amend PO Return costs if the item is standard costed

foundation-database/public/tables/metasql/addresses-detail.mql, foundation-database/public/tables/metasql/contacts-detail.mql, foundation-database/public/tables/metasql/crmaccounts-detail.mql, foundation-database/public/tables/metasql/customers-detail.mql, foundation-database/public/tables/metasql/prospects-detail.mql
Issue requirements related to CRM queries.  Plus this PR provides some examples of its usage.
requires xtuple/qt-client#2195 before this change will work.
=> [33322] Convert some CRM metaSQL over to generic search method

foundation-database/public/patches/task_migration.sql
the time and expense extension won't upgrade properly without this
because the teitem records would point to non-existent or incorrect
task records
=> [34312] update tables with fkeys to prjtask and todoitem allows updating xtte

foundation-database/public/patches/migrate_tax.sql
These RAISE NOTICE calls add communication between the db server and the Updater client during the long-running tax migration process. This prevents the connection from timing out, at least in one test case updating a customer pilot db in the cloud.
=> adding NOTICEs reduces risk of client/server timeout

foundation-database/public/tables/metasql/contacts-detail.mql
to populate required field in Mautic system
=> Mautic Integration: add honorific to contacts-detail metaSQL 

foundation-database/public/tables/metasql/contacts-detail.mql
Include country in the mix
This is still ugly as we are using text not table ids for joins
=> Resolve problematic joins between Address and State. 

foundation-database/public/trigger_functions/bomitem.sql
(cherry picked from commit 0f35e67557b53134c987e840cee27b763ee8e35d)
xtuple/xtuple#3578
=> [18611] Fix Recursive BOM scenario

foundation-database/api/views/armemo.sql
extends #3577 with a CI bug fix
=> [18464] Fix issues with API armemo including sql error and paid amount 

foundation-database/public/patches/populate_charuse.sql
=> [34668] Fix/Update Work Order characteristic configuration demo data

foundation-database/public/tables/metasql/ledgercontrol-detail.mql
see https://github.com/xtuple/xtuple/pull/3588
=> [34212] backport fix

foundation-database/public/functions/woplancost.sql
Code supplied by Jim McC
Also tidy up function formatting to make easier to read
=> [33631] Fix bug with W/O Variance costs

foundation-database/public/trigger_functions/emp.sql
=> [34489] Move employee ancilliary deletions to triggers

foundation-database/public/tables/metasql/creditMemo-editlist.mql
Fix minor typo in metaSQL causing SQL error
=> [34703] Correct sql bug in creditmemo edit metasql

foundation-database/public/tables/metasql/contact-uses.mql
in the Contact relationship list
=> [34782] Add checkbox to show/hide inactive CRM Roles 

foundation-database/public/trigger_functions/item.sql
as tooling items allow inventory
=> [34671] Allow item type changes to tooling when inventory exists

foundation-database/public/tables/metasql/prospects-detail.mql, foundation-database/public/trigger_functions/prospect.sql
Resolves issue where multiple assignment of the same characteristic to a prospect resulted in duplicated rows in the prospects list
=> [34786] Resolve characteristic issues with new Prospects

foundation-database/public/tables/report/PackingList-Shipment.xml
that can cause incorrect shipment lines to be inserted in report.  Cross-contamination between T/Os and S/Os
=> [34813] Resolve issue with PackingList report sql 

foundation-database/public/functions/savetax.sql
Apparently the postgres query optimizer does dumb things with update statements. This change splits one query into two, but speeds up the total function call time from over three minutes to a couple hundred milliseconds on a large database.
=> Fix tax performance issue

foundation-database/public/functions/_docinfo.sql, foundation-database/public/functions/crmaccttypes.sql
=> [35029] Use id instead of name, add user to json

foundation-database/public/patches/task_migration.sql
after task migration to version 5.0.
=> [35095] Resolve comment & characteristic assignment 

foundation-database/public/functions/createprojectfromincident.sql, foundation-database/public/functions/createprojectfromopportunity.sql
from CRM entity.  Fixed initial "from Opportunity" but issue affected "from Incident" as well.
=> [35118] Correct default priority setting when creating Projects 

foundation-database/public/functions/createpr.sql, test/database/functions/createpr.js
cherry-picked 610a33627d2b5241baee88a515485cdb2f6d0fac 17e2ca35bdea76ee1df8b25f96bbb0ac297677e0 289b4a493983061da1bf75344e0e6a56af52e37a  from #3644
=> [34848] forwardport fix from 4_12_x

foundation-database/public/setSearchPath.sql
(cherry picked from commit f64ceb8ad51784b85f2ef14395763b23b24ae8c3)
=> [34230] [Backport] preemptively make admin the owner of public

foundation-database/api/views/armemo.sql
(cherry picked from commit 6bf025cd6ff94e85c595e5d9420b995b9c385ead)
(cherry picked from commit b23e7143e092271e6d5cd0c1057dd272317ab58b)
(cherry picked from commit 3757378b335889916a20e6b1f0cc89d72f3499b0)
=> [18464] [Backport] Fix issues with API armemo including sql error and paid amount

foundation-database/public/trigger_functions/incdt.sql
(cherry picked from commit 23c1a63f45eed56050815c15f7beef9d85610b05)
=> [34055] [Backport] Resolve partial save trigger SQL errors on new Incident

foundation-database/public/functions/_docinfo.sql
(cherry picked from commit 0e8b89b9e043a42941e5eca14f247bd48617613a)
=> [35098] [Backport] Apply provided fix

foundation-database/public/functions/itemipsprice.sql
(cherry picked from commit 5bd78f78d776200e8c0ed9e9fd35187ea4a3f238)
=> [35003] [Backport] Pass in order date to list price ccalculation

foundation-database/public/functions/reversecashreceipt.sql
(cherry picked from commit b15cd3e2dfa70a042ca3a9288dbc4a1ac23b3c11)
=> [35142] [Backport] Check type of original transaction
